### ISSUE TITLE
high temporary space requirement

### ISSUE THREAD

**Issue by p-hofmann** [CAMI-challenge/CAMISIM#1]
Reads of samples are made consecutively and require a lot of space uncompressed.
Currently compression is done after read simulation of all samples is finished.

Space could be saved by compressing reads right after they were generated.

**Comment by abremges** [comment]
@AlphaSquad Please comment if this was implemented or a quick fix possible (compressing each file after each sample). Else, we can clearly state that CAMISIM usually requires **a lot** of space.

**Comment by AlphaSquad** [comment]
A 'quick' fix won't be possible without meddling with a lot of files and scripts. Let's state that CAMISIM requires a lot of space - if you are creating 65 samples with 5GB/sample, you know you will end up with at least 325 GB anyways.
