### ISSUE TITLE
Line 80 KeyError for CAMISIM with new NCBI taxonomy

### ISSUE THREAD

**Issue by ftmashari** [CAMI-challenge/CAMISIM#104]
Hi there,

I am trying to run CAMISIM with the following settings:

> ::::::::::::::
> config.ini
> ::::::::::::::
> [Main]
> seed=123
> phase=0
> max_processors=8
> dataset_id=test
> output_directory=new-simulation
> temp_directory=tmp
> gsa=True
> pooled_gsa=True
> anonymous=True
> compress=1
> [ReadSimulator]
> readsim=CAMISIM/tools/wgsim/wgsim
> error_profiles=
> samtools=CAMISIM/tools/samtools-1.3/samtools
> profile=mbarc
> size=10
> type=wgsim
> fragments_size_mean=300
> fragment_size_standard_deviation=30
> [CommunityDesign]
> distribution_file_paths=id_to_distributions
> ncbi_taxdump=CAMISIM/tools/ncbi-taxonomy_20210324.tar.gz
> strain_simulation_template=CAMISIM/scripts/StrainSimulationWrapper/sgEvolver/simulation_dir
> number_of_samples=1
> [community0]
> metadata=metadata
> id_to_genome_file=id_to_genome_file
> id_to_gff_file=
> genomes_total=1000
> genomes_real=1000
> max_strains_per_otu=1
> ratio=1
> mode=replicates
> log_mu=1
> log_sigma=2
> gauss_mu=1
> gauss_sigma=1
> view=False

> ::::::::::::::
> id_to_distributions
> ::::::::::::::
> AE015928	0.2
> AFBG01000018	0.8
> 

> ::::::::::::::
> id_to_genome_file
> ::::::::::::::
> AE015928	/home/projects/cge/data/metagenomics_pathogen/CAMISIM/all-genomes/AE015928.1.fa
> AFBG01000018	/home/projects/cge/data/metagenomics_pathogen/CAMISIM/all-genomes/AFBG01000018.1.fa

> ::::::::::::::
> metadata
> ::::::::::::::
> genome_ID	OTU	NCBI_ID	novelty_category
> AE015928	1	226186	known_strain
> AFBG01000018	2	999386	known_strain
> 

The two genomes can be downloaded from NCBI with their genome_IDs.
When I run `python2 CAMISIM/metagenomesimulation.py -debug config.ini` I get the following:

> 2021-03-25 13:13:14 ERROR: [Validator 43957622092] Invalid directory
> 2021-03-25 13:13:14 INFO: [MetagenomeSimulationPipeline] Metagenome simulation starting
> 2021-03-25 13:13:14 INFO: [MetagenomeSimulationPipeline] Validating Genomes
> 2021-03-25 13:13:14 INFO: [MetadataReader] Reading file: '/home/projects/cge/data/metagenomics_pathogen/CAMISIM/configfiles/n
> ew-id_to_genome_file'
> 2021-03-25 13:13:15 INFO: [MetadataReader 52127233583] Reading file: '/home/projects/cge/data/metagenomics_pathogen/CAMISIM/c
> onfigfiles/new-metadata'
> 2021-03-25 13:13:15 INFO: [MetadataReader 99218063084] Reading file: '/home/projects/cge/data/metagenomics_pathogen/CAMISIM/n
> ew-simulation/internal/genome_locations.tsv'
> 2021-03-25 13:13:21 INFO: [NcbiTaxonomy] Building taxonomy tree...
> 2021-03-25 13:13:21 INFO: [NcbiTaxonomy] Reading 'nodes' file:	'/scratch/31262996/tmpFbYdt8/NCBI/nodes.dmp'
> 2021-03-25 13:13:38 INFO: [NcbiTaxonomy] Reading 'names' file:	'/scratch/31262996/tmpFbYdt8/NCBI/names.dmp'
> 2021-03-25 13:13:41 INFO: [NcbiTaxonomy] Reading 'merged' file:	'/scratch/31262996/tmpFbYdt8/NCBI/merged.dmp'
> 2021-03-25 13:13:41 INFO: [NcbiTaxonomy] Done (20.0s)
> 2021-03-25 13:13:41 DEBUG: [MetagenomeSimulationPipeline] 
> Traceback (most recent call last):
>   File "CAMISIM/metagenomesimulation.py", line 80, in run_pipeline
>     self.write_profile_gold_standard(meta_data_table, list_of_file_paths_distributions)
>   File "CAMISIM/metagenomesimulation.py", line 203, in write_profile_gold_standard
>     sample_id=""
>   File "/home/projects/cge/data/metagenomics_pathogen/CAMISIM/CAMISIM/scripts/ComunityDesign/taxonomicprofile.py", line 58, i
> n write_taxonomic_profile_from_abundance_files
>     sample_id)
>   File "/home/projects/cge/data/metagenomics_pathogen/CAMISIM/CAMISIM/scripts/ComunityDesign/taxonomicprofile.py", line 89, i
> n write_taxonomic_profile
>     self._stream_taxonomic_profile(stream_output, genome_abundance, metadata_table, sample_id)
>   File "/home/projects/cge/data/metagenomics_pathogen/CAMISIM/CAMISIM/scripts/ComunityDesign/taxonomicprofile.py", line 124, 
> in _stream_taxonomic_profile
>     column_strain_id[row_index] = genome_id_to_strain_id[genome_id]
> KeyError: 'AE015928'
> 
> 
> 2021-03-25 13:13:41 ERROR: [MetagenomeSimulationPipeline] 'AE015928' in line 80
> 2021-03-25 13:13:41 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
> 2021-03-25 13:13:41 INFO: [MetagenomeSimulationPipeline] Temporary data stored at:
> /home/projects/cge/data/metagenomics_pathogen/CAMISIM/tmp/tmptVCqmb

I guess the problem is with my new NCBI_taxdump, because when I run the program with default NCBI_taxdump I do not get this error. But I have no idea how to fix the problem. I have downloaded the newest NCBI_taxdump, untarred it and put it into a folder called NCBI and then tarred and gzipped it again. 

I would appreciate any help on this issue.

Many thanks,
Fatemeh

**Comment by AlphaSquad** [comment]
There seem to be a lot of errors concerning new tax dumps lately, I will have to have a deeper look at that. Here it seems like _some_ path is broken: The first line of the log is `2021-03-25 13:13:14 ERROR: [Validator 43957622092] Invalid directory`, unfortunately I cannot see which directory that is. When the error does not occur with the original taxdump, it might be related to that file. Could you e.g. try the _absolute_ path of the taxdump in the config file?

**Comment by ftmashari** [comment]
Well, I get this "invalid directory" error all the time, but CAMISIM used to produce the output despite this error when I was using old tax dumps. But with new tax dumps, there is another error that stops the code from running: `2021-03-25 13:13:41 ERROR: [MetagenomeSimulationPipeline] 'AE015928' in line 80`

**Comment by AlphaSquad** [comment]
Alright, while I still think that this invalid directory is somewhat strange and might cause problems further downstream, I think I found the `KeyError` problem and fixed it, could you please test this?

**Comment by ftmashari** [comment]
Yes, the keyError is fixed. I will try to fix the Invalid directory error and contact you if I do not succeed.
Thanks for your time Adrian!
