### ISSUE TITLE
 "Key column is not unique! Key: 'Genome2.0'" in line 74

### ISSUE THREAD

**Issue by raquellewei** [CAMI-challenge/CAMISIM#105]
Hi, I was trying to run  "python metagenome_from_profile.py -p defaults/mini.biom" and I got this error message.  I was wondering how I could fix this.
Here are some more details:

Traceback (most recent call last):
  File "./metagenomesimulation.py", line 74, in run_pipeline
    genome_id_to_path_map = self.get_dict_gid_to_genome_file_path()
  File "./metagenomesimulation.py", line 223, in get_dict_gid_to_genome_file_path
    return meta_data_table.get_map(0, 1)

**Comment by AlphaSquad** [comment]
Hi, could you make sure that the output directory is empty (default `out/`)? If that is already the case then I might need some more information by running the command with the `--debug` flag.

**Comment by raquellewei** [comment]
Hi, this resolves the issue. Thank you! (Strange though, for I thought I was running it for the first time so I expected that I didn't need to do anything extra about the out directory)

**Comment by AlphaSquad** [comment]
That is good. Maybe you ran a test run/the "mini" run - that automatically saves into the `out` directory. The `out/` directory is not part of the repository
