### ISSUE TITLE
No enough data to draw

### ISSUE THREAD

**Issue by raquellewei** [CAMI-challenge/CAMISIM#106]
Hi, in reading metadata file, a "not enough data to draw" error was reported. May I know what this error signals and what are the precautions I should take to avoid this from happening? Thank you very much.

**Comment by AlphaSquad** [comment]
This error occurs if the number of genomes in your _metadata file_ is less than the number of strains to be drawn (`genomes_real` and/or `genomes_total` option in the _config file_)

**Comment by raquellewei** [comment]
I see. Thank you.
