### ISSUE TITLE
ERROR Genome Preparation :File does not exist

### ISSUE THREAD

**Issue by Apurbhasaha** [CAMI-challenge/CAMISIM#107]
Hi there,

I am trying to run CAMISIM with the following settings: mini_config_ssdna1.ini 

seed=632741178
phase=0
max_processors=8
dataset_id=RL
output_directory=/gpfs1/data/msb/PEOPLE/saha/cami/genome_test/out_ssdna1
temp_directory=/tmp
gsa=True
pooled_gsa=True
anonymous=True
compress=1

[ReadSimulator]
readsim=/gpfs1/data/msb/tools/camisim/CAMISIM-python3/tools/art_illumina-2.3.6/art_illumina
error_profiles=/gpfs1/data/msb/tools/camisim/CAMISIM-python3/tools/art_illumina-2.3.6/profiles
samtools=/gpfs1/data/msb/tools/camisim/CAMISIM-python3/tools/samtools-1.3/samtools
profile=mbarc
size=0.1
type=art
fragments_size_mean=270
fragment_size_standard_deviation=27

[CommunityDesign]
#distribution_file_paths='out/abundance0.tsv', 'out/abundance1.tsv', 'out/abundance2.tsv', 'out/abundance3.tsv', 'out/abundance4.tsv', 'out/abundance5.tsv', 'out/abundance6.tsv', 'out/abundance7.tsv', '$
ncbi_taxdump=/gpfs1/data/msb/tools/camisim/CAMISIM-python3/tools/taxdump2021.tar.gz
strain_simulation_template=/gpfs1/data/msb/tools/camisim/CAMISIM-python3/scripts/StrainSimulationWrapper/sgEvolver/simulation_dir
number_of_samples=60

[community0]
metadata=/gpfs1/data/msb/PEOPLE/saha/cami/genome_test/metadata_1.tsv
id_to_genome_file=/gpfs1/data/msb/PEOPLE/saha/cami/genome_test/genome_to_id_1.tsv
#id_to_gff_file=
genomes_total=60
genomes_real=60
max_strains_per_otu=1
ratio=1
mode=differential
log_mu=1
log_sigma=2
gauss_mu=1
gauss_sigma=1
view=False

![image](https://user-images.githubusercontent.com/74571252/114692990-705fc580-9d19-11eb-8d5d-2ffbb2e314fa.png)
here is my contains path . but  when i try to run metagenomesimulaton.py i found error that file does not exist.

(venv-camisim) saha@frontend1 /gpfs1/data/msb/tools/camisim/CAMISIM-python3 $ python metagenomesimulation.py /gpfs1/data/msb/PEOPLE/saha/cami/genome_test/mini_config_ssdna1.ini

2021-04-14 11:52:32 INFO: [MetagenomeSimulationPipeline] Metagenome simulation starting
2021-04-14 11:52:32 INFO: [MetagenomeSimulationPipeline] Validating Genomes
2021-04-14 11:52:32 INFO: [MetadataReader] Reading file: '/gpfs1/data/msb/PEOPLE/saha/cami/genome_test/genome_to_id_1.tsv'
**2021-04-14 11:52:33 ERROR: [GenomePreparation] File does not exist: '/gpfs1/data/msb/PEOPLE/saha/cami/genome_test/ssDNA1/Alces-alcesfaecesassociatedmicrovirusMP36497.fasta '**
2021-04-14 11:52:33 ERROR: [MetagenomeSimulationPipeline]  in line 49
2021-04-14 11:52:33 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted

please give me a feedback and a solution .

**Comment by Apurbhasaha** [comment]
here is my genome_to _id path.
x-special/nautilus-clipboard
copy
file:///home/saha/Pictures/Screenshot%20from%202021-04-14%2012-08-23.png

**Comment by AlphaSquad** [comment]
At first glance this seems fine. Could you post your `genome_to_id_1.tsv` file as well?

**Comment by Apurbhasaha** [comment]
Thanks for reply . the file is below here....

x-special/nautilus-clipboard
copy
file:///home/saha/Downloads/genome_to_id_1.tsv

**Comment by AlphaSquad** [comment]
Did the test/example run work (using `python metagenomesimulation.py defaults/mini_config.ini`)?

**Comment by Apurbhasaha** [comment]
Yes, the test run worked before this.

**Comment by AlphaSquad** [comment]
Is it possible that there is a whitespace after the filename?
I really dont know what the problem could be and the error message shows that a whitespace might be there: `'/gpfs1/data/msb/PEOPLE/saha/cami/genome_test/ssDNA1/Alces-alcesfaecesassociatedmicrovirusMP36497.fasta '`

**Comment by Apurbhasaha** [comment]
Thanks for your reply, it's working now.
