### ISSUE TITLE
Error while download viurs geneomes

### ISSUE THREAD

**Issue by LanLei1** [CAMI-challenge/CAMISIM#110]
Hi, I'm trying to simulate a virus dataset using CAMISIM.
`python metagenome_from_profile.py -o out_test -p test/table.from_txt_json.biom -tmp out_test/tmp --community-only `

my biom file is convert from table.txt
`biom convert -i table.txt -o table.from_txt_json.biom --table-type="OTU table" --to-json`

table.txt: 
#OTU ID	Sample1	Sample2	taxonomy
genome1	0.2	0.1	k__Viruses;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;f__Inoviridae;g__Infulavirus;s__Escherichia virus If1
genome2	0.2	0.3	k__Viruses;p__Uroviricota;c__Caudoviricetes;o__Caudovirales;f__Myoviridae;g__Viunavirus;s__Salmonella virus ViI
genome3	0.2	0.3	k__Viruses;p__Uroviricota;c__Caudoviricetes;o__Caudovirales;f__Podoviridae;g__;s__Weissella phage phiYS61
genome4	0.2	0.1	k__Viruses;p__Uroviricota;c__Caudoviricetes;o__Caudovirales;f__Siphoviridae;g__;s__Clostridium phage vB_CpeS-CP51
genome5	0.2	0.2	k__Viruses;p__Uroviricota;c__Caudoviricetes;o__Caudovirales;f__Siphoviridae;g__;s__Streptococcus phage PH15

I can not download these virus genome. The out_test/genomes is empty. 

I can not find 's__Escherichia virus If1' at 'tools/assembly_summary_complete_genomes.txt', this 'assembly_summary_complete_genomes.txt' file only contain 6468 k__Bacteria genomes. But I can find it at 'assembly_summary_chromosome.txt'、'assembly_summary_complete_update.txt' and ‘assembly_summary_scaffold.txt’.

my questions:
1.When we download genemes, we only consider genomes at complete_genomes level? 
2.How to download these virus genomes by metagenome_from_profile.py，can I prepare taxid to sci name to ftp file based on Refseq assembly_summary_refseq.txt?  
3.Can I download these genomes by myself, write these genomes path in 'genome_to_id.tsv', and the prepare 'metadata.tsv'、'abundance*.tsv'; then simulate a virus dataset use
`python metagenomesimulation.py test/config.ini` ?

Thank you very much.

**Comment by AlphaSquad** [comment]
Hi, thank you for you interest in CAMISIM!
The default of CAMISIM is indeed using the complete genomes only.  You can change this using the `-ref` option from the `metagenome_from_profile.py` script and point to the `chromosome` file instead. 
You can of course manually edit these files to include the genomes you want, but - as you point out in question 3 - it might be easier to manually create this data set with exactly the three files you describe. It should work as you describe, please feel free to follow up here if something does not work out as expected.
