### ISSUE TITLE
No such file or directory issue

### ISSUE THREAD

**Issue by naphtap** [CAMI-challenge/CAMISIM#111]
Hello all, 
I installed CAMISIM onto my Linux system and tried running the test set to confirm that CAMISIM installed as intended. I ran the denovo step of CAMISIM using the following command and a series of errors was generated in the screenshots below: 
>> python metagenomesimulation.py defaults/mini_config.ini

![image](https://user-images.githubusercontent.com/13200850/117493889-9441b000-af41-11eb-91e4-e938c33c7aa4.png)

![image](https://user-images.githubusercontent.com/13200850/117494357-36619800-af42-11eb-9d8e-d970629d1bfd.png)

I made sure all the dependencies were installed, but I am running CAMISIM in a conda python2 environment. I am wondering where I can start towards solving this issue.

Thank you for your help!

**Comment by naphtap** [comment]
Sorry for the additional message, but I seem to have solved the problem after reading a prior thread. It seems that the samtools installation provided in CAMISIMs caused the error. I used my own samtools installation and that fixed the error. 

I do have another side question however. Where do I get the OTU ids to fill the metadata table? I can't seem to find OTU ids for specific taxa online so I'm wondering if I just had to to place a random number on the metadata table.

**Comment by AlphaSquad** [comment]
Hi, thanks for your interest in CAMISIM and nice that you got it to run after all. If you did not generate OTUs for your genomes and/or are not interested in just simulating a certain number of genomes per OTU, you can just use random numbers or, what probably makes more sense, number the genomes consecutively.

**Comment by naphtap** [comment]
Thank you for your help! I'm interested in simulating a metatranscriptome sequencing run that generates single-end 75 bp reads. I see that the art_illumina2.3.6 folder contains profiles for pair-ended sequencing. I was wondering if there was a way for me to change the folder files so that I can a) generate single-ended reads and b) change the length of the reads to 75 bp instead.

**Comment by AlphaSquad** [comment]
That is possible, but you would need you own error model trained with ART and supply this error model to CAMISIM via the config file. You should find information on how to do this [here](https://www.niehs.nih.gov/research/resources/software/biostatistics/art/index.cfm)
