### ISSUE TITLE
Metagenome simulation without NCBI_ID

### ISSUE THREAD

**Issue by MDAlamin13** [CAMI-challenge/CAMISIM#112]
Hi,
Is it possible to use the de novo metagenome simulation module (using metagenomesimulation.py ) without specifying the NCBI_ID in the metadata.tsv file? I want to use some simulated sequences as the input reference genomes. As the simulated input sequences do not have any NCBI_ID, is it possible to use them for the de novo metagenome simulation?

**Comment by AlphaSquad** [comment]
Hi, if you are not interested in an accurate profile and just want to do a de novo simulation of your sequences, setting all the NCBI IDs to e.g. 2 (Bacteria) should work; additionally you should set the _max_strains_per_otu_ option to the number of genomes then.

**Comment by MDAlamin13** [comment]
Thank you for your very quick reply.
