### ISSUE TITLE
Feature Request: Utility script to generate random metagenomes

### ISSUE THREAD

**Issue by susheelbhanu** [CAMI-challenge/CAMISIM#116]
Hi, 

Not sure if you already have this, but would it be possible to setup a `utility script` for generating random metagenomes? For example, the user provides a few parameters such as those below:

1. number of genomes
2. number of prokaryotes
3. number of eukaryotes (maybe type of euks)
4. number of strains per genome

I realize that the user has the freedom to provide this via the genome and metadata files, however, having such a utility to randomly pick from NCBI may be useful in the long run. 

Thank you!

**Comment by AlphaSquad** [comment]
That sounds like a useful addition. If you have any suggestions for such a script I'd be happy to have a look

**Comment by susheelbhanu** [comment]
Hahaha not at the moment, but if I do, i'll put it here. Thanks!

**Comment by susheelbhanu** [comment]
For the moment I have a file with the `refseq metadata` where I'm getting my data from and use the following to get a random subset of genomes in a list. the below will of course be adapted for the number of prokaryotes/eukaryotes and the strains. Hope it helps ;)

```
awk -F"\t" '!seen[$9]++' refseq_metadata | awk '$23 ~ /archaea|bacteria|viral/ { print }' | awk 'BEGIN  {srand()} !/^$/  { if (rand() <=.03) print}' | cut -f1,8,9,10,23 | awk -F'\t' -v OFS='\t' '{print "genome"NR, $0}' | head
```
This `awk 'BEGIN  {srand()} !/^$/  { if (rand() <=.03) print}' ` basically prints a random 3% of the lines in the file, which in my case corresponds to ~1000 genomes

**Output**
```
genome1 GCF_005485005.1 2209    2209    Methanosarcina mazei    ./refseq/archaea/GCF_005485005.1/GCF_005485005.1_ASM548500v1_genomic.fna.gz
genome2 GCF_002215285.1 2247    2247    Halorubrum lacusprofundi        ./refseq/archaea/GCF_002215285.1/GCF_002215285.1_ASM221528v1_genomic.fna.gz
genome3 GCF_001266695.1 43687   43687   Metallosphaera sedula   ./refseq/archaea/GCF_001266695.1/GCF_001266695.1_ASM126669v1_genomic.fna.gz
genome4 GCF_005311065.1 161     160     Treponema pallidum subsp. pallidum      ./refseq/bacteria/GCF_005311065.1/GCF_005311065.1_ASM531106v1_genomic.fna.gz
genome5 GCF_003119195.2 1064539 192     Azospirillum brasilense Sp245   ./refseq/bacteria/GCF_003119195.2/GCF_003119195.2_ASM311919v2_genomic.fna.gz
genome6 GCF_000253835.1 887283  195     Campylobacter coli 59-2 ./refseq/bacteria/GCF_000253835.1/GCF_000253835.1_ASM25383v2_genomic.fna.gz
genome7 GCF_000254195.1 887311  195     Campylobacter coli H9   ./refseq/bacteria/GCF_000254195.1/GCF_000254195.1_ASM25419v2_genomic.fna.gz
genome8 GCF_000314145.1 1247732 195     Campylobacter coli BIGS0007     ./refseq/bacteria/GCF_000314145.1/GCF_000314145.1_ASM31414v1_genomic.fna.gz
genome9 GCF_001487085.1 32019   196     Campylobacter fetus subsp. fetus        ./refseq/bacteria/GCF_001487085.1/GCF_001487085.1_17150_1_75_genomic.fna.gz
genome10        GCF_000466925.2 1381117 197     Campylobacter jejuni X  ./refseq/bacteria/GCF_000466925.2/GCF_000466925.2_sequence.fsa_genomic.fna.gz
```
