### ISSUE TITLE
Compressed files as input

### ISSUE THREAD

**Issue by susheelbhanu** [CAMI-challenge/CAMISIM#117]
Hi, 

From the documentation it is unclear whether CAMISIM will take as input compressed fasta files when generated the simulated dataset. Example: can I used `fna.gz` files as obtained from refseq or should they be uncompressed prior to specifying the paths in the genome_to_id and metadata files?

If not, could this be implemented sometime in the future?

Thank you!

**Comment by AlphaSquad** [comment]
Right now CAMISIM expect the files to be of `fasta` format, but allowing zipped fasta files should also be a possibility, I agree

**Comment by susheelbhanu** [comment]
Thanks for clarifying that. 👍
