### ISSUE TITLE
Fasta name-entry formatting

### ISSUE THREAD

**Issue by joacjo** [CAMI-challenge/CAMISIM#119]
Hi and thank you for a super useful tool! 

I have had issues with making the de-novo profiling work on a list of genomes with a strange error during the anonymization step. Turned out it might be due to "dashes" (-) in the fasta entries names i.e. MGV-GENOME-999
Replacing dashes with dots (.) or removing them made me able to complete the pipeline succesfully. 

I just wanted to let you know.

Best,
Joachim

**Comment by AlphaSquad** [comment]
Thank you very much for the information! I have seen similar things happen and thought I fixed all these cases, but seems I have to get back to the drawing board. Is it feasible for you to replace the dashes in the fasta names in the meantime?

**Comment by joacjo** [comment]
No worries at all. I just removed the dashes and that fixed the problem. It's also possible to replace them with "dots", that works too.
