### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: synonym.spname, synonym.taxid

### ISSUE THREAD

**Issue by thh32** [CAMI-challenge/CAMISIM#120]
When running the test code `sudo docker run -it -v "/media/thomashitch/MyDATA/Projects/MIMIC/Artificial_data/CAMISIM/defaults:/input:rw" -v "/media/thomashitch/MyDATA/Projects/MIMIC/Artificial_data/CAMISIM:/output:rw"  cami/camisim:latest  metagenome_from_profile.py -p /input/mini.biom -o /output` in docker I get the following error;

```
NCBI database not present yet (first time used?)
Downloading taxdump.tar.gz from NCBI FTP site...
Done. Parsing...
Loading node names...
2369433 names loaded.
316758 synonyms loaded.
Loading nodes...
2369433 nodes loaded.
Linking nodes...
Tree is loaded.
Updating database: /root/.etetoolkit/taxa.sqlite ...
2369000 generating entries... 
Uploading to /root/.etetoolkit/taxa.sqlite

Inserting synonyms:      80000Traceback (most recent call last):
  File "metagenome_from_profile.py", line 11, in <module>
    import scripts.get_genomes as GG
  File "/usr/local/bin/scripts/get_genomes.py", line 15, in <module>
    ncbi = NCBITaxa()
  File "/usr/local/lib/python2.7/dist-packages/ete2/ncbi_taxonomy/ncbiquery.py", line 74, in __init__
    self.update_taxonomy_database()
  File "/usr/local/lib/python2.7/dist-packages/ete2/ncbi_taxonomy/ncbiquery.py", line 101, in update_taxonomy_database
    update_db(self.dbfile)
  File "/usr/local/lib/python2.7/dist-packages/ete2/ncbi_taxonomy/ncbiquery.py", line 659, in update_db
    upload_data(dbfile)
  File "/usr/local/lib/python2.7/dist-packages/ete2/ncbi_taxonomy/ncbiquery.py", line 698, in upload_data
    db.execute("INSERT INTO synonym (taxid, spname) VALUES (?, ?);", (taxid, spname))
sqlite3.IntegrityError: UNIQUE constraint failed: synonym.spname, synonym.taxid
```
It appears to be an issue with the NCBI taxa files (https://github.com/Prunoideae/MitoFlex/issues/2), has anyone else experienced this and what could be done to solve this?

Thanks,
Tom

**Comment by AlphaSquad** [comment]
It's not a stupid question at all, I am unfortunately not an expert on docker myself. 
It should not really be dependent on docker though. If you cloned this repository then just using `git checkout -b python3` before running your docker command in the path you cloned CAMISIM to should switch the branch.

**Comment by AlphaSquad** [comment]
Did that work?

**Comment by fplaza** [comment]
Hi,
This problem is solved with the Python3 branch.
It would be great to update the image available on Docker Hub as the current version does not work.

Florian

**Comment by delahondes** [comment]
As Florian said at GMT Science we managed to create an updated version of the Dockerfile based on Ubuntu 20.04 (instead of Ubuntu 16.04). The main trick was to add "libncursesw5" (which is a hidden dependancy of samtools) in the apt install line (and remove ete2 patching as the python3 branch is using ete3).

**Comment by AlphaSquad** [comment]
`python3` has been merged into `master`. I will be closing this, the `docker` issue will remain open until I created a tag and updated on dockerhub
