### ISSUE TITLE
ERROR: 13

### ISSUE THREAD

**Issue by GKerdivel** [CAMI-challenge/CAMISIM#121]
Hello,
I am desperately trying to simulate some datasets with CAMISIM since a few days. After correcting bunches of bugs I finally reach an error with simply written "ERROR: 13" and no other clue about what is the problem or in which script the problem is... Do you know what this problem is and how to solve it?
Thanks in advance
Best regards

**Comment by AlphaSquad** [comment]
Okay, that sounds good! I will close this issue then, but feel free to open a new one if something is amiss.
