### ISSUE TITLE
libncurses is missing in the Docker image

### ISSUE THREAD

**Issue by fplaza** [CAMI-challenge/CAMISIM#125]
Hi,

A colleague fo mine built a docker image from with the python3 branch of CAMISIM.

It seems that libncurses is required but missing.
`/usr/local/bin/tools/samtools-1.3/samtools: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory`

Could you add it to the recipe?

Best,
Florian

**Comment by AlphaSquad** [comment]
I will look into it, thanks for bringing it to my attention (also #120 )

**Comment by fplaza** [comment]
And finally, it would be great to include a pre-built database for ete3.
Currently, it is generated during the first execution.

Thanks again,
Florian

**Comment by AlphaSquad** [comment]
Optimally there would be a prompt whether to build a new database or use an existing pre-built one. Providing databases which become outdated pretty quick comes with its own set of problems.

**Comment by AlphaSquad** [comment]
I uploaded a new version/tag to dockerhub (1.3.0), please feel free to test whether it works for you!
