### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by AlphaSquad** [CAMI-challenge/CAMISIM#13]
Since we have a new and shiny text about the Simpipeline for the CAMI paper it would be great to incorporate this into the wiki, i.e. removing the nested structure of the documentation and instead have one central text in which all the relevant information is found, linking to external sources only (?)

**Comment by AlphaSquad** [comment]
This Issue is actual again since the addition of the new features!

**Comment by abremges** [comment]
@AlphaSquad What's the current status? At first glimpse, looking good. However, if you need help with the wiki, please let me, @pbelmann, ... know and we can jump in!

**Comment by AlphaSquad** [comment]
A file of files for improving documentation (#35 ) should be handy, and maybe somewhere more information for people wanting to work/code with CAMISIM? User documentation should be fine I hope
