### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by AlphaSquad** [CAMI-challenge/CAMISIM#14]
For all ways to invoke the pipeline and all data sets we create, we should provide exemplary config files which should work out of the box

**Comment by abremges** [comment]
I think we should provide the config files for CAMI1 (if they still work), the new toy datasets, and CAMI2 eventually—these cover the most common use cases.

**Comment by AlphaSquad** [comment]
Should these be shipped in an own folder within CAMISIM? Additionally, a default config file is already available which can be edited according to the desired data set.
CAMI1 config files should still work but I haven't tried in a while.

**Comment by abremges** [comment]
Or provided on data.cami-challenge.org, alongside the toy dataset they belong to.
		
		

		
	




On Thu, Mar 8, 2018 at 4:02 PM +0100, "Adrian Fritz" <notifications@github.com> wrote:












Should these be shipped in an own folder within CAMISIM? Additionally, a default config file is already available which can be edited according to the desired data set.

CAMI1 config files should still work but I haven't tried in a while.

**Comment by abremges** [comment]
To be checked with https://github.com/CAMI-challenge/CAMISIM/issues/33, the config files used for simulation should be included in the toy datasets' folders already.

**Comment by abremges** [comment]
Taken care of w/ @asczyrba @AlphaSquad
