### ISSUE TITLE
denovo community design

### ISSUE THREAD

**Issue by laxMax** [CAMI-challenge/CAMISIM#141]
Hi, I am using the CAMISIM and I am really appreciating your efforts!
I was wondering if I could just use a file-path-to-genome-id and a metadata.csv file to run de novo metagenome simulation? If so, what if my selected genomes, which are newly discovered sequences, have no NCBI id & taxid to be assigned in the column 3 of metadata.csv file, which requires NCBI taxonomy identifier? Should I make up a taxonomy file for all of my novel genomes?

Thanks for reading, looking forward to your reply!

**Comment by AlphaSquad** [comment]
Hi, thank you for the warm words!
It is possible to run CAMISIM just using a genome to id and a metadata file - CAMISIM will then draw abundances randomly from a log-normal distribution. There are default parameters for the distribution, but you can also modify them in the config file.
If you use newly sequenced genomes and are not interested in the profiling gold standard CAMISIM produces, then you can just use arbitrary (but valid) taxonomy IDs, for example `2` for bacteria.
