### ISSUE TITLE
No module named Bio

### ISSUE THREAD

**Issue by kangxiongbin** [CAMI-challenge/CAMISIM#144]
**I encounter an issue:**

2022-11-12 09:40:00 INFO: [MetagenomeSimulationPipeline] Anonymize Data
2022-11-12 09:40:00 INFO: [FastaAnonymizer] Interweave shuffle and anonymize
Traceback (most recent call last):
  File "/homes/kang/software/CAMISIM/anonymizer.py", line 8, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'

**But when I check, my python have the module:**
kang@porta:sim-meta-small-illuma$ python
Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio import SeqIO
>>> 

Do you know how to deal with it? Thank you very much!

Best,
Xiongbin

**Comment by AlphaSquad** [comment]
Hm, it is hard to tell why that happens, Ionly have two hypothesis: Do you run CAMISIM in a conda environment or maybe with another python version which is different from the one you show?
