### ISSUE TITLE
Data availability for CAMISIM Figure 3 

### ISSUE THREAD

**Issue by paulinetrinh** [CAMI-challenge/CAMISIM#156]
Hi! I was wondering if the data used to generate Figure 3 top left panel looking at genome fraction (%) and coverage when using MEGAHIT (1.0.3) was available publicly somewhere from the 2019 CAMISIM paper (https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-019-0633-6)? Or if there was any guidance on how to generate those curves somewhere in the repository? 

It would be incredibly helpful to use that data in testing a method that I'm developing but I haven't been able to figure out where it might be or if there is a quick way to generate those curves. 

Thank you! 
Pauline

**Comment by AlphaSquad** [comment]
Hi - yes, all the data for the plots from the CAMISIM publication is available in this github repository: https://github.com/CAMI-challenge/CAMISIM-DATA, for figure 3 it should be in the coverage_sweep folder. I hope you find everything you need there

**Comment by paulinetrinh** [comment]
Fantastic!! Thanks so much for your help
