### ISSUE TITLE
Python Requirements

### ISSUE THREAD

**Issue by pbelmann** [CAMI-challenge/CAMISIM#16]
It would make it for the user easier to use metasim if it would contain a requirements.txt. This file just states the needed libraries with their version numbers. 

A user would just have to type:

~~~BASH
pip install -r requirements.txt
~~~

in order to install metasim with all libraries.

**Comment by abremges** [comment]
Was this resolved via https://github.com/CAMI-challenge/CAMISIM/pull/25? If so, close this issue upon merging https://github.com/CAMI-challenge/CAMISIM/pull/25.

**Comment by pbelmann** [comment]
Since PR #25 is quite old it must be checked before merge.

**Comment by abremges** [comment]
Who should review it? @AlphaSquad?

**Comment by pbelmann** [comment]
I will build it

**Comment by AlphaSquad** [comment]
Sorry, I cannot recall why we didn't merge this before. It can still be merged without conflict, @pbelmann did you try this version? If yes, I can immediately merge it, closing #15 and #16

**Comment by abremges** [comment]
Resolved by https://github.com/CAMI-challenge/CAMISIM/pull/25
