### ISSUE TITLE
"ncbi_taxdump=tools/ncbi-taxonomy_20170222.tar.gz"  Unsupported newer version.

### ISSUE THREAD

**Issue by NickShanyt** [CAMI-challenge/CAMISIM#160]
Hi,
I downloaded the newer version of _taxdump_, actually the latest version,updated in 20230711.

when I ran it with the default version in the "tool/ncbi-taxonomy_20180226.tar.gz",it reported like that :

![image](https://github.com/CAMI-challenge/CAMISIM/assets/42581222/9b10b3a0-b33d-4387-a868-db9f1da28291)

I thought may it not fit my data's newer taxid.

so I want to update _taxdump_,however, it reported like that :
![image](https://github.com/CAMI-challenge/CAMISIM/assets/42581222/9cf54ef8-3db6-4790-b3ed-b2159d8ae4df)

I checked the newer version of _taxdump_, and the file "taxidlineage.dmp" does exist.

 I'm not sure why

**Comment by NickShanyt** [comment]
in this way:

`python metagenomesimulation.py test/5-2636-2.ini`

**Comment by AlphaSquad** [comment]
Unfortunately there is an odd requirement for a CAMISIM's taxdumps, namely there being a folder `NCBI` within the zipped taxdump, so unfortunately you would have to unzip your taxdump, put it in a folder named `NCBI` and then zip it again. I am sorry for the hassle, please report back if that worked

**Comment by NickShanyt** [comment]
Many thanks for your quickly reply.After testing, it works.
Indeed, this is an aspect that is not easy to notice.
When I compared the file contents and found a difference, there was indeed an extra layer of folders, but it didn't catch my attention.


————————————————————————
And
I need some help with the configuration file.
I tested different parameters of 
`genomes_total=5
genomes_real=5
number_of_samples=5`

now I know `number_of_samples` decide home many samples will be simulated.
`genomes_total` decide home many Genoms will be selected randomly from _metadata.tsv_ & _genome_to_id.tsv_, but I don't understand what would `genomes_real=5` change.
And I tested it but find nothing different.


>

**Comment by AlphaSquad** [comment]
CAMISIM offers the possibility to simulate strains using [sgEvolver](https://darlinglab.org/mauve/developer-guide/benchmarking.html) from the mauve suite. If you define `genomes_real` to be less than `genomes_total`, then CAMISIM will simulate the difference in strains. If this is of no interest to you, then you can just keep `genomes_real = genomes_total`

**Comment by NickShanyt** [comment]
> CAMISIM offers the possibility to simulate strains using [sgEvolver](https://darlinglab.org/mauve/developer-guide/benchmarking.html) from the mauve suite. If you define `genomes_real` to be less than `genomes_total`, then CAMISIM will simulate the difference in strains. If this is of no interest to you, then you can just keep `genomes_real = genomes_total`

I am not sure if I understand correctly. For example, if I define `genomes_real=20` and `genomes_total=30`, does it mean that the program will simulate 10 (30-20=10)genomes based on the provided 20 genomes ?
Also, when I set the parameters as mentioned above, both parameters in the `config.ini` file in the out folder are set to the same value, which is 30.

**Comment by AlphaSquad** [comment]
Yes, in theory that is what should happen, I am confused that it did not work. Though the numbers in the output `config.ini` are not necessarily _wrong_: After the genomes have been simulated they are treated as regular input genomes, so if you want to re-run your simulation, it would be correct to use 30 for `genomes_real` because it would count the newly simulated genomes as "real" for the next run. You would have to check either the log of CAMISIM whether genomes were simulated and/or whether simulated genomes appear in the `metadata.tsv`/`genome_to_id.tsv` and the `genomes` folder CAMISIM creates

**Comment by NickShanyt** [comment]
> Yes, in theory that is what should happen, I am confused that it did not work. Though the numbers in the output `config.ini` are not necessarily _wrong_: After the genomes have been simulated they are treated as regular input genomes, so if you want to re-run your simulation, it would be correct to use 30 for `genomes_real` because it would count the newly simulated genomes as "real" for the next run. You would have to check either the log of CAMISIM whether genomes were simulated and/or whether simulated genomes appear in the `metadata.tsv`/`genome_to_id.tsv` and the `genomes` folder CAMISIM creates

I check the genomes folder and the sequence files in there are all selected from my maetadata.

Ignoring this for now, I now have a new problem that arises when I add some new sequences as community2 ......
![image](https://github.com/CAMI-challenge/CAMISIM/assets/42581222/175e85d4-8770-4745-afee-6432066fb73a)

**Comment by AlphaSquad** [comment]
Oh wow, this whole thread is really a deep dive into functionalities of CAMISIM which are not used very often. It seems like the option to _not_ anonymize the data set (you probably set this option to False?) is incompatible with creating multiple communities. I fear that if you want to simulate multiple communities _and_ have non-anonymized reads, you will have to set the abundances of your second community manually. Alternatively it _should_ work when turning anonymization on.

**Comment by NickShanyt** [comment]
> Oh wow, this whole thread is really a deep dive into functionalities of CAMISIM which are not used very often. It seems like the option to _not_ anonymize the data set (you probably set this option to False?) is incompatible with creating multiple communities. I fear that if you want to simulate multiple communities _and_ have non-anonymized reads, you will have to set the abundances of your second community manually. Alternatively it _should_ work when turning anonymization on.

Sorry I'm a little late in replying.
The one I mentioned wasn't actually a problem with CAMISIM itself, I located and fixed it myself. The problem was due to the presence of a "-" in the sequence ID, and Samtools was reporting an error for this problem.

**Comment by AlphaSquad** [comment]
Yeah, unfortunately there are some problems with special signs in sequence IDs, I am glad you got that figured out.
