### ISSUE TITLE
attempting to simulate viral community, continue to encounter an error

### ISSUE THREAD

**Issue by icbarron** [CAMI-challenge/CAMISIM#164]
I'm attempting to perform a de novo simulation of a viral community, and I continue to encounter this error:

```
2023-08-29 14:39:38 INFO: [MetagenomeSimulationPipeline] Metagenome simulation starting
2023-08-29 14:39:38 INFO: [MetagenomeSimulationPipeline] Validating Genomes
2023-08-29 14:39:38 INFO: [MetadataReader] Reading file: '/home/FCAM/ibarron/CAMISIM/defaults/id_to_genome_file.tsv'
2023-08-29 14:39:38 ERROR: [GenomePreparation] File does not exist: '/home/FCAM/ibarron/CAMISIM/GCF_012271565.1_ASM1227156v1_genomic.fna'
2023-08-29 14:39:38 ERROR: [MetagenomeSimulationPipeline]  in line 49
2023-08-29 14:39:38 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
```

here's my config

```
[Main]
seed=632741178
phase=0
max_processors=8
dataset_id=RL
output_directory=out
temp_directory=/tmp
gsa=True
pooled_gsa=True
anonymous=True
compress=1

[ReadSimulator]
readsim=tools/art_illumina-2.3.6/art_illumina
error_profiles=tools/art_illumina-2.3.6/profiles
samtools=tools/samtools-1.3/samtools
profile=mbarc
size=0.1
type=art
fragments_size_mean=270
fragment_size_standard_deviation=27

[CommunityDesign]
#distribution_file_paths=out/abundance0.tsv,out/abundance1.tsv,out/abundance2.tsv,out/abundance3.tsv,out/abundance4.tsv,out/abundance5.tsv,out/abundance6.tsv,out/abundance7.tsv,out/abundance8.tsv,out/abundance9.tsv
ncbi_taxdump=tools/ncbi-taxonomy_20170222.tar.gz
strain_simulation_template=scripts/StrainSimulationWrapper/sgEvolver/simulation_dir
number_of_samples=10

[community0]
metadata=defaults/jmt_mock_community_genomes.tsv
id_to_genome_file=defaults/id_to_genome_file.tsv
id_to_gff_file=
genomes_total=60
num_real_genomes=48
max_strains_per_otu=1
ratio=1
mode=differential
log_mu=1
log_sigma=2
gauss_mu=1
gauss_sigma=1
view=False
```

![image](https://github.com/CAMI-challenge/CAMISIM/assets/121980481/0cdb9b5f-81a3-4f8a-b679-eac4ba93eefd)
the genomes are all there, too.

**Comment by AlphaSquad** [comment]
Hey, thank you for your interest in CAMISIM. Is it correct that the genomes are just in the main directory of CAMISIM (in your case `/home/FCAM/ibarron/CAMISIM/`)?

**Comment by icbarron** [comment]
They're located in ```/home/FCAM/ibarron/CAMISIM/defaults/genomes```

**Comment by AlphaSquad** [comment]
By default CAMISIM is using the taxonomy stored in `tools/ncbi-taxonomy_20170222.tar.gz` which is from 2017, so probably the ID for the genome was not present in 2017. Currently there is two ways around that:
1. You provide your own, recent taxonomy (with the `ncbi_taxdump` option). This has to be a `tar.gz` file with a `NCBI` subfolder
2. If you do not need a taxonomic profile gold standard, you can change the taxonomy IDs of the genomes which produce errors (or all of them as that is probably easier) to an arbitrary, existing one (e.g. `2` for Bacteria)
