### ISSUE TITLE
the details in simulating the madness dataset of CAMI II by CAMISIM 

### ISSUE THREAD

**Issue by fanqiedantang** [CAMI-challenge/CAMISIM#165]
Hi，
I want to know the  details in simulating the madness dataset of CAMI II by CAMISIM in order to design my community. But I didn't find any details in the supplementary information of the CAMI II article，as showing in the following fig. Thank you for your help！
![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/49f25bb0-7e6c-4db8-9cb2-18fa4f6216e7)

**Comment by fanqiedantang** [comment]
> Hi, all the data with which CAMISIM was run can be found on publisso here: https://repository.publisso.de/resource/frl%3A6425521 The details for the strain madness data set explicitely are here: https://frl.publisso.de/data/frl:6425521/strain/ The genomes used for simulation are in the main folder, the setup for CAMISIM in the individual folders for short/long/hybrid simulation, e.g. https://frl.publisso.de/data/frl:6425521/strain/short_read/strmgCAMI2_setup.tar.gz I hope this helps

Thank you very much for the information you provided, which has been very helpful to me. Another question is whether the principle of its community design is the same as that of the marine and plant associated dataset, or is there any other basis for your design？

**Comment by AlphaSquad** [comment]
In contrast to the marine and plant data sets where we started off with a BIOM profile from the respective environment, the strain data set does not start from a profile, but uses a lognormal distribution and the [_differential_](https://github.com/CAMI-challenge/CAMISIM/wiki/Distribution-of-genomes) mode for simulation.
The genomes present are mainly from human-associated diseases though

**Comment by fanqiedantang** [comment]
> In contrast to the marine and plant data sets where we started off with a BIOM profile from the respective environment, the strain data set does not start from a profile, but uses a lognormal distribution and the [_differential_](https://github.com/CAMI-challenge/CAMISIM/wiki/Distribution-of-genomes) mode for simulation. The genomes present are mainly from human-associated diseases though

I understand. Thank you very much !

**Comment by fanqiedantang** [comment]
could you  tell me the specific parameters of lognormal distribution? I noticed the lognormal distribution with parameters: mean=1.5 , standard deviation = 1, in the high complexity dataset of CAMI. And have you retained the following settings:for each five consecutive samples, abundances for the next sample were calculated by sampling new values from the log-normal distribution, adding these to the previous value and dividing by two.

**Comment by AlphaSquad** [comment]
For CAMI 2 the CAMISIM default was used, i.e. sigma = 2 and mu = 1. The differential mode states that the abundances are drawn from the log-normal distribution independently every sample (so no, these settings were not retained).

**Comment by fanqiedantang** [comment]
thanks！
I have another question, can we design strain heterogeneity in simulations based on BIOM profiles (such as the design of marine datasets)? And does CAMISIM have specific parameters available for the use?

**Comment by AlphaSquad** [comment]
Starting from a BIOM profile is not directly compatible with simulating strain heterogeneity. If strain variation is present in your BIOM profile, CAMISIM will try to download multiple strains as well if they exist in the NCBI database; there are no guarantees though. You could however run the `from_profile` script with the `-d` option which only performs community design. You can then edit the resulting configuration files and "manually" simulate strains for your environment

**Comment by fanqiedantang** [comment]
> Starting from a BIOM profile is not directly compatible with simulating strain heterogeneity. If strain variation is present in your BIOM profile, CAMISIM will try to download multiple strains as well if they exist in the NCBI database; there are no guarantees though. You could however run the `from_profile` script with the `-d` option which only performs community design. You can then edit the resulting configuration files and "manually" simulate strains for your environment

thanks a lot !

**Comment by fanqiedantang** [comment]
Hi，
Now I have encountered a new problem. I want to design a dataset with multiple samples, where there is heterogeneity between samples (bacteria of the same genus but different species).  Can the - s parameter of the 'from profile' script automatically generate the dataset I want? Or should I manually design the BIOM for each sample first and then use "from profile“ script to generate each sample one by one. If the - s parameter of the "from profile" script is used, what is the specific heterogeneity in these samples? For example, if there are 100 bacteria in each sample, 70 bacteria are common, 10 bacteria are unique, and 20 bacteria belong to the same genus but different species, can this standard be customized?

**Comment by AlphaSquad** [comment]
The `-s` option of the `from_profile` simulation just controls the number of samples to be created by CAMISIM, if you do not want to create _all_ samples from a single BIOM profile. Using different communities it _could_ be possible to do a simulation like you imagine - if I understood correctly - somehwat automatically, but from the sounds of it, it will probably easier to manually design the profiles, I am sorry.

**Comment by AlphaSquad** [comment]
If you have additional questions regarding the simulation, feel free to re-open, closing this for now
