### ISSUE TITLE
Question, is there any existing repository.

### ISSUE THREAD

**Issue by shanoudi** [CAMI-challenge/CAMISIM#167]
Hi,
I am wondering if there are already publicly available datasets created using CAMISIM.
I would like to analyze the output before going throw the installation of CAMISIM.
Best,

**Comment by AlphaSquad** [comment]
Hi,
there are actually quite a few. The first two are published alongside the CAMISIM publication itself (https://doi.org/10.1186/s40168-019-0633-6):
1. A 65-sample mouse gut data set: https://repository.publisso.de/resource/frl:6421672
2. A 49-sample from different sites from the human microbiome project: https://repository.publisso.de/resource/frl:6425518

and then for the CAMI 2 challenge (https://doi.org/10.1038/s41592-022-01431-4):

3. The CAMI 2 challenge data sets (10-sample marine data set, 21-sample plant-associated, 100-sample "strain madness"): https://repository.publisso.de/resource/frl:6425521

**Comment by shanoudi** [comment]
Thanks,

**Comment by shanoudi** [comment]
Hi,
A few days ago, I was able to open the links. I can not open them today. Can you check them from your end?

**Comment by AlphaSquad** [comment]
The links work for me

**Comment by AlphaSquad** [comment]
Currently CAMISIM does not have a mode for simulating RNA/Metatranscriptome data, but this is actually planned/work in progress and may be possible early next year!

**Comment by shanoudi** [comment]
Thank you,
