### ISSUE TITLE
Hi,I still cant understand what "adundance" means …………

### ISSUE THREAD

**Issue by NickShanyt** [CAMI-challenge/CAMISIM#170]
Hi, in my own project, RPM is often used for abundance estimation, but I don't understand what 'abundance' means in the distribution_*.txt file.

In other words, I want to compare the results of my RPM with the RPM of the gold standard with one of the several species that are simulated in a sample, what could I do?

Thx

**Comment by AlphaSquad** [comment]
All the abundances CAMISIM reports are "genome-wide" and as far as I understand RPM/RPKM are metrics for specific genes. Information about how the abundance works can be found [here](https://github.com/CAMI-challenge/CAMISIM/wiki/File-Formats#outdistributionsdistribution_itxt)
