### ISSUE TITLE
some error when i  try the command ----  "python metagenome_form_profile.py -p defaults/mini.biom " 

### ISSUE THREAD

**Issue by fanqiedantang** [CAMI-challenge/CAMISIM#172]
Hi，

![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/bcdf851b-20b9-4839-b2d3-9511c3be86ef)

thank you for your help！

**Comment by AlphaSquad** [comment]
Hi,
it seems like your `/tmp` directory is almost full/too small to hold the expected size of the simulated data set. You will have to allocate more space or choose another directory
