### ISSUE TITLE
Input genomes

### ISSUE THREAD

**Issue by CassandraHjo** [CAMI-challenge/CAMISIM#174]
In my simulation I want to use my MAGs as input. These are not complete genomes, but instead fasta files containing multiple contigs like this (header starts with >):
>MAG0001_1
ATCGATCGATCGATCGATCG
ATCGATCGATCGATCGATCG
>MAG0001_2
ATCGATCGATCGATCGATCG
ATCGATCGATCGATCGATCG

Do i need to concatenate the contigs before using them as input genomes in the simulation, or can I use the MAG fasta files as they are? If I use the files as they are, will I get overlapping reads between the contigs or will the simulated reads come from separate contigs?

**Comment by AlphaSquad** [comment]
CAMISIM will work with these fasta files, but it will sample from every sequence individually, i.e. not create reads spanning different contigs.

**Comment by CassandraHjo** [comment]
How are the ends of the contigs handled?

**Comment by AlphaSquad** [comment]
That is up to the actual simulator you are using. In general with random sampling from the genome you would expect them to be covered less
