### ISSUE TITLE
Meaning of community parameters in config file

### ISSUE THREAD

**Issue by CassandraHjo** [CAMI-challenge/CAMISIM#176]
Do these parameters in the config file affect the results from the simulation when running differential abundance mode? Or only when running replicates mode?

```
gauss_mu=1
gauss_sigma=1
```

**Comment by AlphaSquad** [comment]
These parameters only change the distribution in the replicates mode, in the differential abundance mode all the abundances are drawn from the lognormal distribution (defined with `log_mu` and `log_sigma`)
