### ISSUE TITLE
Is profile-based design with custom genomes possible?

### ISSUE THREAD

**Issue by CassandraHjo** [CAMI-challenge/CAMISIM#177]
I want to use my own fasta files as input genomes to the simulation. I am wondering if profile-based community design is possible with custom genomes. i.e. I do not want to use genomes from NCBI. Would it be an option to provide my own genome sequence collection in the profile based design, like I can do in the de-novo based design?

**Comment by AlphaSquad** [comment]
Actually this is possible, yes! You will need to use the `-ar`/`--additional-references` option. This file has to be in a tab-separated format with the 4 columns NCBI_ID Scientific_name genome_path novelty_category (without header). The NCBI ID is required for mapping the scientific name from the profile to your genome, for novelty category you can just use `known_strain`.
If you do not want to use genomes from the NCBI at all, you will additionally need to use the `-ref`/`--reference-genomes` option and point to an empty file, so CAMISIM does not use the default reference list in addition to the one provided for you. The command could look like this:
`./metagenome_from_profile --additional-references /your/reference/file.tsv --reference-genomes /path/to/empty/file.tsv -p /your/profile.biom`

**Comment by CassandraHjo** [comment]
I am not interested in gsa or pooled_gsa. Do I still need to find a unique NCBI ID or can I just use 2?

For example in the reference_file.tsv can an entry look like this?
`2    MAG0001    genomes/MAG0001.fasta    known_strain`

**Comment by AlphaSquad** [comment]
You don't need to provide these NCBI IDs then, so yes it could look like this, though just to be safe I'd advise using absolute paths to your genomes.

**Comment by CassandraHjo** [comment]
What does the biom file need to contain if an entry in the reference file looks like the one above?

**Comment by fanqiedantang** [comment]
> Actually this is possible, yes! You will need to use the `-ar`/`--additional-references` option. This file has to be in a tab-separated format with the 4 columns NCBI_ID Scientific_name genome_path novelty_category (without header). The NCBI ID is required for mapping the scientific name from the profile to your genome, for novelty category you can just use `known_strain`. If you do not want to use genomes from the NCBI at all, you will additionally need to use the `-ref`/`--reference-genomes` option and point to an empty file, so CAMISIM does not use the default reference list in addition to the one provided for you. The command could look like this: `./metagenome_from_profile --additional-references /your/reference/file.tsv --reference-genomes /path/to/empty/file.tsv -p /your/profile.biom`
how the “Scientific_name” can be manually set?

**Comment by CassandraHjo** [comment]
I do not have the NCBI ID for all my custom genomes. Is there another way to make the profile-based design work, or is de-novo design (which I am able to run) be the best option?

**Comment by AlphaSquad** [comment]
Since you do not use CAMISIM's option to download genomes the _de novo_ design might actually be best (and more accurate). To use the abundances from the input profile you would need to use the `distribution_file_paths` option to provide them for your genomes, tab-separated with genome ID and abundance from the BIOM file. Note that for the _de novo_ design to work you will still need to provide NCBI taxonomy IDs, but if you do not plan on using the taxonomic profile gold standard any valid NCBI ID should work (e.g. `2` for Bacteria)

**Comment by CassandraHjo** [comment]
The _de novo_ design simulation is running for my custom genomes, when using 2 as NCBI 

In the config file under `[CommunityDesign]`, how do I specify the `distribution_file_paths=`? Is this a path to a folder with all the files ?

**Comment by CassandraHjo** [comment]
Do I need to change the phase in the config file if I am using the `distribution_file_path `option?

**Comment by AlphaSquad** [comment]
No, you should not need to change the phase, CAMISIM will automatically use the files if they are provided. Note that for multiple samples these need to be absolute paths and comma-separated without whitespace:
`distribution_file_paths=/path/to/sample1.tsv,/path/to/sample2.tsv`

**Comment by CassandraHjo** [comment]
Should the tsv files include headers?

**Comment by AlphaSquad** [comment]
No, these do not need a header, just genome_ID and abundance tab-separated
