### ISSUE TITLE
ERROR: [MetagenomeSimulationPipeline] 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte in line 49？

### ISSUE THREAD

**Issue by fanqiedantang** [CAMI-challenge/CAMISIM#180]
![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/c4d65599-f7c2-403e-bed1-a12b35e65dcc)

**Comment by AlphaSquad** [comment]
It seems like a file you provide in the `genome_to_id.tsv` file is not `utf-8` encoded.

**Comment by fanqiedantang** [comment]
I tried this command on both servers, but one reported this error and the other did not. My `genome_ to_ id.tsv` has not been modified.

**Comment by AlphaSquad** [comment]
From the looks of it the problem does not lie within the `genome_to_id.tsv` file but in one of the genomes you use (e.g. the sequence name is not `utf-8` encoded). If that is not the case, it is very hard to debug if it works on one server but not the other - you might have to resort to running it on the one where it works.
