### ISSUE TITLE
How to map relevant genomes to OTU through scientific names？

### ISSUE THREAD

**Issue by fanqiedantang** [CAMI-challenge/CAMISIM#185]
command: 
> python metagenome_from_profile.py -p small_test/test.biom -c small_test/config_test.ini --ncbi ncbi/ -f --debug -ref small_test/ref.tsv -tmp small_test/tmp -o small_test/out/

warning:
![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/acad070f-f5e4-48be-ae07-6d290ddb5b48)
![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/c1d0e6b6-7223-490e-a13e-01b6b7e02d33)

the "ref.tsv" :
![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/fdf44908-b985-4992-9966-f43c6846e533)
The scientific name in the ref.tsv file is obtained by searching the taxonomy of each OTU on NCBI. But it seems that they cannot map OTUs to the correct reference genome through them.

**Comment by AlphaSquad** [comment]
The mapping with scientific names currently only works with the online version of NCBI, the additional reference file is not used for the scientific name mapping. If you already _know_ which genomes you want to use/which genomes map to which in your BIOM file, it is probably better to use the _de novo_ simulation of CAMISIM and just set the abundances given in the profile - also see the last few answers of [this issue](https://github.com/CAMI-challenge/CAMISIM/issues/177) for more details on how to do this.

**Comment by fanqiedantang** [comment]
Thank you very much, I understand what you mean now. By the way, if i don't know which genomes map to my BIOM file,  how can I solve the following warning:
![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/eb321e94-f374-4cb5-9892-2ddbdfda65e8)
![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/ab8a9c07-f195-43ba-b0c7-073043e815c1)
![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/288c5975-b42f-4bbd-aa2e-018c1d1741cb)

**Comment by AlphaSquad** [comment]
These warnings should not stop CAMISIM from running, they just show you that the NCBI mapping failed and CAMISIM uses the additional references to fill up your data set - which means that the data set might be less similar to your BIOM profile then desired. Another way to get a little bit more accuracy is to edit the file `scripts/get_genomes.py` on line 47 and set `MAX_RANK` to e.g. `order` or `class` (this seems to be the level where your genomes have "real" scientific names) - but that means CAMISIM might only find genomes of the same `order`/`class` as your BIOM profile genomes - which is quite the difference.
Now, if you know the mapping for some genomes and do not for others, you can run CAMISIM from profile with the `community_only` option. This will yield a mapping file for _all_ genomes, you can then replace this mapping for the genomes you do know the mapping and use CAMISIMs mapping for the others and use this as input for a _de novo_ run. I hope this helps.

**Comment by fanqiedantang** [comment]
Thank you!

**Comment by fanqiedantang** [comment]
when i try :`python metagenomesimulation.py small_test/de_novo_config.ini -debug -log test.log`

**Comment by fanqiedantang** [comment]
it seems that there are some new errors when i try the de_novo simulation command:`python metagenomesimulation.py MP_simulation/config.ini --debug`.

**Comment by AlphaSquad** [comment]
This error is most likely to occur when there is a previous/unfinished CAMISIM run in your `out` directory. Could you make sure that the `out` directory is empty and try again?

**Comment by fanqiedantang** [comment]
ok ,but it will take some time.
Meanwhile, I encountered another error while running this command. 
![image](https://github.com/CAMI-challenge/CAMISIM/assets/90701916/349e48a7-3731-4cd4-ab11-69f0a8a45892)
My files have not been modified.

**Comment by fanqiedantang** [comment]
Hi, i noticed the same problem in thiss tissue[https://github.com/CAMI-challenge/CAMISIM/issues/76#issuecomment-638981852] (url). I tried simulating 1GB, 5GB, 20GB, and 50GB, but all reported the same error. I don't think this problem was posed by the deep/GB per sample .

**Comment by AlphaSquad** [comment]
Since this error occurs during anonymising, could you try running CAMISIM without anonymising and see if you still encounter errors?

**Comment by fanqiedantang** [comment]
how to run CAMISIM without anonymising？

**Comment by fanqiedantang** [comment]
Strangely, when I chose to simulate 10 species from all, there was no error.
