### ISSUE TITLE
the data type of CAMISIM long read dataset 

### ISSUE THREAD

**Issue by Wenhai-Zhang** [CAMI-challenge/CAMISIM#188]
The CAMISIM long read dataset such as strain-madness, is Pacbio CLR long read simuated with pbsim?

**Comment by AlphaSquad** [comment]
Yes, the CAMI 2 challenge data sets were simulated using PBSim. You can find the CAMISIM config files used for simulating them in the publisso repository: https://frl.publisso.de/data/frl:6425521/, for the long read strain madness e.g. this one: https://frl.publisso.de/data/frl:6425521/strain/long_read/strmgCAMI2_setup.tar.gz
