### ISSUE TITLE
Confused by the abundance values in the CAMI2 toy datasets

### ISSUE THREAD

**Issue by TakacsBertalan** [CAMI-challenge/CAMISIM#189]
Hi!
I would like to generate samples based on the distribution of the CAMI2 toy datasets (human gastrooral to be specific) and I am a bit confused by the abundance values in the abundance*.txt and distribution_*.txt files. I assumed that they were relative abundance values, as the Wiki and other issues in this repository seem to suggest. But simply adding up the values doesn't equal to 1 or 100, they sum up to 363. So right now I am a bit confused: where does this value come from?

Thanks,
Bertalan Takács

**Comment by AlphaSquad** [comment]
Hi,
"relative abundance" here just means that it describes the abundance relative to each other, the numbers themselves do not have a specific meaning though. You could divide all abundances by 3.63 and get abundances which sum up to 100 if you need this.
