### ISSUE TITLE
Example Pipeline Call

### ISSUE THREAD

**Issue by pbelmann** [CAMI-challenge/CAMISIM#19]
The Usage section 
https://github.com/CAMI-challenge/MetagenomeSimulationPipeline/wiki/User-manual#usage should be updated:

e.g.

~~~BASH
python metagenome_from_profile.py path/to/16Sprofile
~~~

should be

~~~BASH
python metagenome_from_profile.py -p path/to/16Sprofile
~~~

**Comment by AlphaSquad** [comment]
Yes, thanks, the wiki needs quite an overhaul I think!

**Comment by AlphaSquad** [comment]
Updated this, but wiki still needs some work

**Comment by abremges** [comment]
Continues in https://github.com/CAMI-challenge/CAMISIM/issues/13, closing this.
