### ISSUE TITLE
metagenomesimulation.py raising "ERROR: [MetagenomeSimulationPipeline] 'gb|*********.1|:1-****' in line 117" Error

### ISSUE THREAD

**Issue by cberta11** [CAMI-challenge/CAMISIM#192]
Good afternoon,
After successfully running metagenomesimulation.py on the provided sample dataset in defaults/mini_config.ini, I am having issues with running the script on my own genomes. Running metagenomesimulation.py with default/mini_config.ini containing paths to my own genomes returns:
![image](https://github.com/user-attachments/assets/3bc8078a-a840-4395-bf13-be11e05399d5)
while running metagenomesimulation.py with defaults/default_config.ini, with similar parameters, likewise returns
![image](https://github.com/user-attachments/assets/8035b3ce-4a65-48f0-8e47-7be2a4db84c4)
I am unsure what is causing the error, and as I said running the script on mini_config with the example data set you provided ran without issue. Any help would be greatly appreciated.
Joe

I provided the following below for your convenience:
1.) metagenomesimulation.py defaults/mini_config.ini --debug print out
2.) defaults/mini_config.ini used
3.) metagenomesimulation.py defaults/default_config.ini --debug print out
4.) defaults/default_config.ini used
5.) mamba environment packages
6.) metadata.tsv used
7.) genome_to_id.tsv used

1.) metagenomesimulation.py defaults/mini_config.ini --debug print out
![image](https://github.com/user-attachments/assets/8a9bc747-03c6-4c77-96b5-8a1d677e2d8d)

2.) defaults/mini_config.ini used
![image](https://github.com/user-attachments/assets/8046d416-d927-4514-8671-d1790a8fd863)

3.) metagenomesimulation.py defaults/default_config.ini --debug print out
![image](https://github.com/user-attachments/assets/37ea3c57-3989-489e-bd4b-3a5c211c0e3b)

4.) defaults/default_config.ini used
![image](https://github.com/user-attachments/assets/15865826-f415-417e-818f-0aae409fc745)

5.) packages list for the mamba environment used
![image](https://github.com/user-attachments/assets/a2ab6ddf-84b7-462a-b2ea-3eb8d8e50bda)

6.) metadata.tsv used
![image](https://github.com/user-attachments/assets/3019d3a1-57dc-4dc8-be2a-3008f0e20e46)

7.) genome_to_id.tsv used
![image](https://github.com/user-attachments/assets/4f86126d-dfe5-4629-8b86-2ec36d97897a)

**Comment by cberta11** [comment]
I also thought to try setting anonymous reads to false since the issue seems to come from that portion of the metagenomesimulation.py script:
![image](https://github.com/user-attachments/assets/b1feb1a9-b0da-44a0-98a5-4164b0a9555f)

However, this just threw the flag:
![image](https://github.com/user-attachments/assets/6326ecd0-b2a1-4515-9ffe-b17123d01ef1)
 
So it seems to throw the error with whatever comes after the assembly stage?

**Comment by AlphaSquad** [comment]
Unfortunately, CAMISIM has some problems with special characters in sequence names - I assume the obscure error message you receive (`gb|OL88421.1|:1-1451_2`) is a sequence name in the Acidovorax caeni genome. I thought I had fixed that error in the latest version, but it still seems to pop up from time to time. It should work if you remove all `-` (and maybe also `_` just to be sure) from the sequence names within the fasta file(s).
