### ISSUE TITLE
Read simulators

### ISSUE THREAD

**Issue by p-hofmann** [CAMI-challenge/CAMISIM#2]
Currently only Art Illumina is implemented in this version.
- [pIRS](https://code.google.com/p/pirs/) requires a configuration file generated dynamically for each strain. A nice method needs to be written for that.
- [PBSIM](https://code.google.com/p/pbsim/) does not create sam files but maf files. The script _maf_converter.py_ has been written to convert those maf files into sam files, but still needs to be made look nice. Making a class for all the loose functions, etc.
- The code of the class for both [PBSIM](https://code.google.com/p/pbsim/) and [pIRS](https://code.google.com/p/pirs/) still needs to be cleaned up similar to _ReadSimulationArt_.

All scripts can be found in the module _scripts.ReadSimulationWrapper_

This mostly a todo for myself, if I feel the need to do something more fun than documenting stuff.

**Comment by AlphaSquad** [comment]
By now, wgsim, ART, NanoSim and PBsim (163750) are included and fully functional
