### ISSUE TITLE
Log File

### ISSUE THREAD

**Issue by AlphaSquad** [CAMI-challenge/CAMISIM#20]
For very large metagenomes the log files get incredibly large, need to set an option for no or minimal logging.

**Comment by abremges** [comment]
Can you quantify “incredibly”? Is this merely annoying or a deal-breaker?

**Comment by fungs** [comment]
Quick fix: directly compress with gzip, text files usually compress really well. Long term: have standard python verbosity levels in the logger, this only works if the written information is under your control, not so much for wrapped programs (unless they have verbosity levels as well).

**Comment by AlphaSquad** [comment]
The final log for the mousegut data was 500MB, which is not something you want to open with gedit but will not bust your memory either.

**Comment by abremges** [comment]
Small enough, I wouldn't bother.
