### ISSUE TITLE
ReadSimulation random seed

### ISSUE THREAD

**Issue by AlphaSquad** [CAMI-challenge/CAMISIM#22]
The reads for every genome are simulated with different seeds (based on the original "overall" seed). This makes kind of sense for multi-sample experiments, so that not for every sample the same reads are produced but makes it really hard to exctly recreate the SAME data set a second time.

**Comment by AlphaSquad** [comment]
-wgsim seed does not seem to work
-NanoSim has no seed option: Add a patch/maybe pull request

**Comment by abremges** [comment]
What about PBsim?

**Comment by AlphaSquad** [comment]
I couldn't reproduce the wgsim problem (seed is working as expected), PBsim seed is also working. In both test cases, exactly the same data set was created, even with multiple samples.

**Comment by koadman** [comment]
a common pitfall for seed saving strategies like this run is when the underlying PRNG changes. If read simulators are using rand() from the C library for example, then different systems with different C lib rand() implementations can produce different results. Could be worth checking where the different read simulators and other stochastic bits get their randomness from.

**Comment by abremges** [comment]
Thanks, @koadman, but this is somewhat beyond our control and scope.
For CAMI, should we e.g. also state the OS, GCC, ... versions we used?
I think full reproducibility on *one* system is a realistic milestone to reach.

---

Anyway, I implemented the ``--seed``option to NanoSim and created a PR: https://github.com/bcgsc/NanoSim/pull/24
In the meantime, @AlphaSquad, please give https://github.com/abremges/NanoSim a try.

**Comment by koadman** [comment]
yeah, it's not a small problem. Back when I wrote sgEvolver I pulled in some 3rd party Mersenne twister code so the PRNG was guaranteed but to solve this for CAMI something similar would have to happen in all of the dependency programs. agree, recording the software environment versions is the most practical way forward.

**Comment by AlphaSquad** [comment]
NanoSim also uses numpy random at one position in the code. I also added a seed to numpy random (and had to fix the saved seeds to be less than 2**32 - 1 in CAMISIM). This recreates the same data sets with CAMISIM + NanoSim

**Comment by abremges** [comment]
Thanks.
