### ISSUE TITLE
ete2 ftp usage

### ISSUE THREAD

**Issue by AlphaSquad** [CAMI-challenge/CAMISIM#26]
ete2/3 uses ftp for accessing the NCBI data base which might not be possible if using it behind a proxy.
Probably needs a PR for ete2/3

**Comment by abremges** [comment]
How much work is this? From my point of view, this is somewhat beyond our control and not really within CAMISIM's scope. I suggest to simply state that we rely on ete2/3 to download NCBI genomes (which is an optional feature anyway).

**Comment by AlphaSquad** [comment]
Agreed, there does not seem to be an easy solution.
