### ISSUE TITLE
log to file

### ISSUE THREAD

**Issue by AlphaSquad** [CAMI-challenge/CAMISIM#27]
Since the logs are gigantic, it might be useful if the logs are automatically written to a file, i.e. in encapsulated environments where stdout/stderr is not really a possibility.

**Comment by abremges** [comment]
What's the current status? @AlphaSquad please close resolved issues.

**Comment by abremges** [comment]
Related to https://github.com/CAMI-challenge/CAMISIM/issues/20

**Comment by abremges** [comment]
One can always redirect, closing (for now).
