### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by abremges** [CAMI-challenge/CAMISIM#30]
CAMISIM should be versioned following the semantic versioning conventions: http://semver.org/
Pragmatically, I suggest to simply start with 1.0.0 once we merged https://github.com/CAMI-challenge/CAMISIM/pull/29 into the master branch..?

**Comment by AlphaSquad** [comment]
Agreed. Previous versions, mentioned in the manuscript, have been tagged as 0.* versions but can be re-tagged as 1.0.0-alpha/beta as required by semver. 
The current version runs stably and is able to produce all public data sets, so assigning 1.0.0 to the version of paper submission also seems sensible to me.

**Comment by AlphaSquad** [comment]
1.0.0 is out and the changelog up-to-date
