### ISSUE TITLE
NCBI taxonomy versions

### ISSUE THREAD

**Issue by AlphaSquad** [CAMI-challenge/CAMISIM#32]
The provided NCBI taxonomy dump version(s) might be incompatible with the list for downloading genomes resulting in pipeline crashes

**Comment by abremges** [comment]
Please double-check! This is critical.

**Comment by AlphaSquad** [comment]
This is fixed with the addition of the new taxonomy dump (c6e04d452e6781d93c43ba94d2da25523e552a88).
