### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by abremges** [CAMI-challenge/CAMISIM#34]
@pbelmann You created a new Docker container for CAMISIM, correct?
We might want to include a link to the Docker Hub URL in the manuscript.
Can you take care of registering it there and provide us with a working link?

I guess this is stalled by PR https://github.com/CAMI-challenge/CAMISIM/pull/25 and https://github.com/CAMI-challenge/CAMISIM/pull/29 (and not much can be done now).

**Comment by AlphaSquad** [comment]
The docker container was tested and PR #25 merged into aedit.
