### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by AlphaSquad** [CAMI-challenge/CAMISIM#36]
CAMISIM should also provide a description of data sets created by it (similar to #35 but for the produced data not the code itself)

**Comment by abremges** [comment]
Removed this from v1.0 milestone, confused this issue with the (manual) data set descriptions for https://data.cami-challenge.org/participate
I agree, however, that CAMISIM should produce such a metadata file in future releases, will make things easier for the upcoming CAMI 2 data sets.

**Comment by AlphaSquad** [comment]
Added with version [1.1.0](https://github.com/CAMI-challenge/CAMISIM/releases/tag/1.1.0)
