### ISSUE TITLE
Error in readsimulationwrapper.py

### ISSUE THREAD

**Issue by FlyinTeller** [CAMI-challenge/CAMISIM#37]
There is a type in line 1058 in scripts/ReadSimulationWrapper/readsimulationwrapper.py:

`fragment_size_mean=options.fragments_size_mean,`
should be 
`fragment_size_mean=options.fragment_size_mean,`

**Comment by AlphaSquad** [comment]
Thank you, good catch. I will not commit a hotfix right now though:
Please note that this line is in the main()-function of the readsimulationwrapper.py script. This function is not used anywhere within CAMISIM.
The usage of the readsimulationwrapper as standalone script is a feature which we are not actively maintaining and it is likely that this option is gone in future versions especially if more bugs pop up.

**Comment by AlphaSquad** [comment]
The possibility of using the readsimulationwrapper as standalone has (at least temporarily) been removed. If there is interest in the re-addition of this feature, please stay in touch and we will try to reimplement it.
