### ISSUE TITLE
full list of dependencies with versions

### ISSUE THREAD

**Issue by nick-youngblut** [CAMI-challenge/CAMISIM#40]
I'd like to create a conda recipe for `CAMISIM` and add it to the bioconda channel. It would be helpful to know the full list of dependencies and the (minimum) required versions for each (eg., the versions for Mothur, MUMmer, ART, etc). I've been looking at the wiki, dockerfile, etc, and I can't find all of the software versions required.

**Comment by AlphaSquad** [comment]
Sorry, it seems I overlooked this issue until now.
Right now, CAMISIM employs a mixture of shipping software within CAMISIM (e.g. ART, MUMmer, Mothur) and requiring the user to have them installed locally (e.g. NanoSim, PBsim and whats listed in the [requirements.txt](https://github.com/CAMI-challenge/CAMISIM/blob/master/requirements.txt)).
We tested our [docker container](https://github.com/CAMI-challenge/CAMISIM/blob/master/Dockerfile) and it works with the given requirements.txt plus the pre-installed software. Is this a solution which could also work for bioconda?

**Comment by nick-youngblut** [comment]
Thanks for the info! I don't see any version requirements for ART, MUMmer, etc. in your requirements .txt or docker container. The version requirements are very important to include in conda recipes in order to prevent bugs resulting from using old versions of particular software (eg., conda would use an old version of ART that's already installed in an existing conda environment *unless* the CAMISIM recipe *specifically requires* a more up-to-date version)

**Comment by AlphaSquad** [comment]
Yes, there are no version requirements there, because the versions required for CAMISIM are already provided within CAMISIM ([here](https://github.com/CAMI-challenge/CAMISIM/tree/master/tools)). Installing CAMISIM thus automatically includes the required versions of the aforementioned tools.

**Comment by nick-youngblut** [comment]
I didn't see that you bundle all of the dependency software with CAMISIM. That's a lot of software to keep bundled with yours! You could remove them and just require the specific conda versions of each software, but that would require conda.

**Comment by AlphaSquad** [comment]
Yeah, we are looking into different options right now on how to get rid of the bundled software. Is it possible to create a conda recipe from the current status?

**Comment by nick-youngblut** [comment]
Yeah, it should be possible. It is rather easy, since you have all of the bioinfo software deps bundled with `CAMISIM`. The recipe wouldn't be much more complicated if the software isn't bundled (instead, just more conda packages listed in the yaml).

**Comment by nick-youngblut** [comment]
Are there any plans to convert `CAMISIM` into a python package (eg., with a `setup.py` file) that will be uploaded to pypi? This would be very helpful.

**Comment by AlphaSquad** [comment]
Unfortunately that is not planned right now, but I will look into it, thanks for the suggestion!
