### ISSUE TITLE
What is

### ISSUE THREAD

**Issue by Xudangliatiger** [CAMI-challenge/CAMISIM#41]
I want it generate  metagenome data sets with tags，like a fastq file with sequences and a csv file which shows different clustering name( mapping the sequences id in fq file。。。。) But i was confused because the description of input file and output file，it was tooo difficult for a CS student to figure out the differences ..... How can I get the data I want

**Comment by AlphaSquad** [comment]
Hey,
unfortunately I don't entirely understand what kind of data you want. If you neither have genomes nor a profile you want to simulate from available, then no current mode of CAMISIM will be able to simulate something. If you have some genomes you are interested in, then you can run the de novo mode, a default config is available [here](https://github.com/CAMI-challenge/CAMISIM/blob/master/defaults/default_config.ini), you will need to fill in the blanks, i.e. output directory and the metadata.tsv and genome_to_id.tsv files.
If you have a BIOM profile you are interested in, then you can just run the from_profile mode and the default_config is automatically used, you probably should reduce the data set size though.

**Comment by Xudangliatiger** [comment]
HELLO！Thanks for your answer anyway. So your idea is  if I want the dataset ,I had to get some BIOM profile or something like that？ By the way ，may you tell me a little more about the mategenome data，like where do you always go to got  them for recent research？The data problems keep me up at night this week :(

**Comment by AlphaSquad** [comment]
Sorry, it is really hard to find out what you actually want. If you want a metagenome data set you either need a profile to simulate from or genomes you want to have in your metagenome, yes. You can easily get genomes/profiles from NCBI, the Human Microbiome Project (HMP) or similar projects; but this is outside the scope of CAMISIM.
