### ISSUE TITLE
Questions related to metadata

### ISSUE THREAD

**Issue by kmin940** [CAMI-challenge/CAMISIM#43]
Hi, I'm trying to simulate a dataset using CAMISIM but since I am relatively new to metagenomics, I do not have clear understandings on some names. My questions are :

1) I want to use genome with ncbi accession GCF_000006825.1, so I visited 
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/006/825/GCF_000006825.1_ASM682v1
From this site, do I only need to download 
 GCF_000006825.1_ASM682v1_genomic.fna.gz (genome sequence)
 GCF_000006825.1_ASM682v1_genomic.gff.gz (genome annotation)
and add the paths to id_to_genome and id_to_gff respectively?

2) I'm not sure what these 4 fields mean for metadata. i.e. Row 1 (header): genome_ID\tOTU\NCBI_ID\tnovelty_category
What is genome ID for GCF_000006825.1? Where can I find this information?
What is tOTU for GCF_000006825.1? Where can I find this information?
I found from https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=272843 that taxonomy identifier for GCF_000006825.1 is 272843.
What should I put for tnovelty_category?

It would also be great if you can provide some other concrete example genome with the corresponding genome_ID\tOTU\NCBI_ID\tnovelty_category.
Thank you very much for your help.

**Comment by kmin940** [comment]
Thank you very much for your detailed answer. I've tried to run metagenome simulation, but got an error. 
Here is my configuration file located at /home/mathed/CAMI:
`seed=1
phase=0
max_processors=4
dataset_id=sample_1
output_directory=/home/mathed/CAMI
temp_directory=/home/mathed
gsa=False
pooled_gsa=False
anonymous=True
compress=1
readsim=/home/mathed/CAMISIM/tools/art_illumina-2.3.6/art_illumina
error_profiles=/home/mathed/CAMISIM/tools/art_illumina-2.3.6/profiles
samtools=/home/mathed/CAMISIM/tools/samtools-1.3/samtools
profile=mbarc
size=1
type=art
fragments_size_mean=100
fragment_size_standard_deviation=5
ncbi_taxdump=/home/mathed/CAMISIM/tools/ncbi-taxonomy_20170222.tar.gz
strain_simulation_template=/home/mathed/CAMISIM/scripts/StrainSimulationWrapper/sgEvolver/simulation_dir
number_of_samples=1
metadata=/home/mathed/CAMI/metadata
id_to_genome_file=/home/mathed/CAMI/genome_to_id.tsv
id_to_gff_file=/home/mathed/CAMI/id_to_gff.tsv
genomes_total=9
genomes_real=5
max_strains_per_otu=5
ratio=1
mode=replicates
log_mu=1
log_sigma=2
gauss_mu=1
gauss_sigma=2
view=True`


This is my genome_to_id file with path /home/mathed/CAMI/genome_to_id.tsv
`GCF_000006825	/home/mathed/Strains/GCF_000006825.1_ASM682v1_genomic.fna
GCF_000009545	/home/mathed/Strains/GCF_000009545.1_ASM954v1_genomic.fna
GCF_000255915	/home/mathed/Strains/GCF_000255915.1_ASM25591v1_genomic.fna
GCF_000259545	/home/mathed/Strains/GCF_000259545.1_ASM25954v1_genomic.fna
GCF_000975325	/home/mathed/Strains/GCF_000975325.1_ASM97532v1_genomic.fna`


This is my id_to_gff_file with path /home/mathed/CAMI/id_to_gff.tsv
`GCF_000006825	/home/mathed/Strains/GCF_000006825.1_ASM682v1_genomic.gff
GCF_000009545	/home/mathed/Strains/GCF_000009545.1_ASM954v1_genomic.gff
GCF_000255915	/home/mathed/Strains/GCF_000255915.1_ASM25591v1_genomic.gff
GCF_000259545	/home/mathed/Strains/GCF_000259545.1_ASM25954v1_genomic.gff
GCF_000975325	/home/mathed/Strains/GCF_000975325.1_ASM97532v1_genomic.gff`


This is my metadata with path /home/mathed/CAMI/metadata
`GCF_000006825	/home/mathed/Strains/GCF_000006825.1_ASM682v1_genomic.gff
GCF_000009545	/home/mathed/Strains/GCF_000009545.1_ASM954v1_genomic.gff
GCF_000255915	/home/mathed/Strains/GCF_000255915.1_ASM25591v1_genomic.gff
GCF_000259545	/home/mathed/Strains/GCF_000259545.1_ASM25954v1_genomic.gff
GCF_000975325	/home/mathed/Strains/GCF_000975325.1_ASM97532v1_genomic.gff`

And this is the code and error message
$ python /home/mathed/CAMISIM/metagenomesimulation.py /home/mathed/CAMI/configuration
ERROR: /home/mathed/CAMI/configuration
What have I done wrong?

2.Also, can I generate paired-end reads? How can I generate it?
3.Can I get access to coverage that will be generated by reads simulator of each strain in each sample?
4.What does community mean? What is the difference between community and samples?
5.Also in the configuration file, dataset_id=sample_1, and number_of_samples=1. What should I put for dataset_id if I have number_of_samples=2? Do I put dataset_id=sample_1,sample_2?

Thank you very much.

**Comment by AlphaSquad** [comment]
Hi, unfortunately this is quite hard to read (markdown does not handle tabs very well). 
Since these questions are also not really "code-related": Could you send me these questions via Mail (adrian.fritz at helmholtz-hzi.de) so we can talk in detail there?

**Comment by kmin940** [comment]
ok! Thank you very much. I will send images of my files.

**Comment by kmin940** [comment]
I've sent the mail. Can you take a look at it? Thank you.
