### ISSUE TITLE
Errors in open file 

### ISSUE THREAD

**Issue by ShoshanaHu** [CAMI-challenge/CAMISIM#45]
I have followed the user manual but there appeared an error when running CAMISAM. 
The input file was a biom file produced by Metaphlan2 with the command: 
./metagenome_from_profile.py -p ~/CAMISIM_test/read_1.biom -o ~/CAMISIM_test/output/
When the Simulating reads finished, there appeared an error like the following: 
**2019-02-13 04:25:38 INFO: [GenomePreparation 27474285647] Simulating reads finished
[E::hts_open_format] fail to open file '/home/swy/CAMISIM_tmp/tmpnfPzsh/2019.02.13_04.06.47_sample_0/reads/k__Bacteria'
samtools view: failed to open "/home/swy/CAMISIM_tmp/tmpnfPzsh/2019.02.13_04.06.47_sample_0/reads/k__Bacteria" for reading: No such file or directory
/bin/sh: f__Enterobacteriaceae: command not found
/bin/sh: p__Proteobacteria: command not found
/bin/sh: p__Proteobacteria: command not found
/bin/sh: o__Enterobacteriales: command not found
/bin/sh: o__Enterobacteriales: command not found
/bin/sh: c__Gammaproteobacteria: command not found
/bin/sh: f__Enterobacteriaceae: command not found
/bin/sh: s__Klebsiella_pneumoniae.0.sam: command not found
/bin/sh: c__Gammaproteobacteria: command not found
/bin/sh: g__Klebsiella: command not found
/bin/sh: s__Klebsiella_pneumoniae.0.bam: command not found**
........

I don't know where the error occurred that caused the error report. I hope you can give me some advice. Thank you very much!

**Comment by AlphaSquad** [comment]
Thank you for your interest. I just wrote an email to you as well. Could you provide me with the biom file you used? I assume that the error comes from an biom file which provides the taxonomy in a different way than expected.
