### ISSUE TITLE
USE OF CAMISIM

### ISSUE THREAD

**Issue by Shirley-Q** [CAMI-challenge/CAMISIM#47]
Now I have Metagenome raw data with fastq and many genomes using metabat. I don't know how to use CAMI. should i make input folder？which files should folder contain？Thank you very much！
>> python metagenome_from_profile.py -p path/to/16Sprofile

>> python metagenomesimulation.py configuration/metagenome_simulation

>> python genomeannotation.py configuration/genome_annotation

**Comment by AlphaSquad** [comment]
Thank you for your interest in CAMISIM. To find out how to use CAMISIM, plesae first check the [user manual](https://github.com/CAMI-challenge/CAMISIM/wiki/User-manual).
You will either need a set of genomes and have to decide on your on distribution of these genomes or a BIOM profile.

**Comment by AlphaSquad** [comment]
We need to create a more user friendly manual, this is also addressed in #48 , closing this for now
