### ISSUE TITLE
Tutorial or Example for denovo simulation

### ISSUE THREAD

**Issue by mladen5000** [CAMI-challenge/CAMISIM#48]
I was attempting to use CAMISIM and I have read the user manual and readme but I am still not sure exactly what the input file for de novo metagenome simulation would look like. Is there any step by step guide, or example input files available for the metagenomesimulation.py?

**Comment by AlphaSquad** [comment]
Hi, thank you for your interest in CAMISIM.
The denovo simulation uses as input just the configuration file and a set of taxonomically classified genomes. 
A default configuration file is available in defaults/default_config.ini. You will need to set a few lines in that file:
In the [Main] section, you need to set the output directory:
`output_directory=/path/to/output/`
In the [CommunityDesign] section you need to set the number of samples you want to simulate and the size in Gbp _per sample_ 
`size=1`
`number_of_samples=1`
In the [community0] section, you need to set paths to two files (which you also need to create):
`metadata=/path/to/metadata.tsv`
`id_to_genome_file=/path/to/genome_to_id.tsv`
These files are described [here](https://github.com/CAMI-challenge/CAMISIM/wiki/File-Formats)
Additionally you need to set the number of genomes which should be used:
`genomes_total=`
`num_real_genomes=`
If you want to use all your genomes and don't want to simulate artificial ones, you can set both these to the number of your available genomes.
Finally, if you chose to simulate more than one sample, you need to set the mode for abundance calculation which is one of these four: 
`mode=` one of `replicates` / `timeseries_lognormal` / `timeseries_normal` / `differential`
Apart from that, the defaults should be enough for a first run to see if CAMISIM is working.
After these files have been created and the options set, you should be able to run CAMISIM with:
`./metagenome_from_profile.py defaults/default_config.ini`

**Comment by AlphaSquad** [comment]
A more detailed manual/quickstart guide is certainly required, I will look into creating one. 
Meanwhile please ask if there still is anything unclear, thanks!

**Comment by mladen5000** [comment]
Thank you for the clarification.

I have a few more questions regarding the specifics of the user-created .tsv files:
metadata Tab separated data table It maps genome ids with additional information of their classification. For example, I am currently trying to create a simple simulated dataset that is composed of 5 different reference genomes, I would like to create a dataset sampled from 5 reference genome fasta files I have on my machine. 

1. Is the genome id user defined, and if so, does it take a string, integer etc?
2. In this specific example, what would I define as column 2? If all of these 5 genomes are various strains of the same species, do I provide the same OTU for each row?
3. In this specific example what do I place into column 4? 

I think a simple example of the .tsv files, even showing a few rows of each file, would be very helpful and could be added to the user documentation.

Thank you!

**Comment by AlphaSquad** [comment]
> 1. Is the genome id user defined, and if so, does it take a string, integer etc?

Yes it is. Names can be arbitrary strings (i.e. also strings which entirely consist of numbers).

> 2. In this specific example, what would I define as column 2? If all of these 5 genomes are various strains of the same species, do I provide the same OTU for each row?

That depends what you want to achieve. If you want to use all of your genomes anyways, it makes sense to assign every genome its own OTU (i.e. number them in ascending order).
CAMISIM will only draw a certain number of genomes from a single OTU, this number can be set using the max_strains_per_otu option.

> 3. In this specific example what do I place into column 4?
The novelty category is described [here](https://github.com/CAMI-challenge/CAMISIM/wiki/Novelty-Category). This option is only relevant if you have genomes not present in NCBI and you don't want to simulate all of your genomes. In your case, setting the novelty category to "known_strain" for all genomes should suffice.

I will upload exemplary genomes, metadata and genome_to_id files for a small example (for which the BIOM file already is present).

**Comment by AlphaSquad** [comment]
Added an exemplary run with 2846150 and described it's use in the [usage section of the readme](https://github.com/CAMI-challenge/CAMISIM/wiki/User-manual#usage)
Please tell me if this answers your questions

**Comment by MDAlamin13** [comment]
Hi,

Sorry for bringing out this old thread. Can you please explain how can I get the OTU value for each of my genomes? I have 10 genomes from 10 species. I want to create a simulated dataset only from those genomes. I got the rest of the part of the default configuration file for the denovo mode except the second column of the metadata.tsv file where I need to put the OTU values for each of my genomes. Where can I get those values?

**Comment by AlphaSquad** [comment]
Hi,
the OTU is interally only used to limit the number of genomes from a certain OTU (the `max_strains_per_otu` option). If you want to use all 10 genomes anyway, then you can just assign every genome their own OTU, i.e. just numbering them from 1 to 10.

**Comment by MDAlamin13** [comment]
Perfect. Thank you so much for your quick response :)
