### ISSUE TITLE
Error while running "python metagenomesimulation.py defaults/mini_config.ini" command

### ISSUE THREAD

**Issue by drashutosh** [CAMI-challenge/CAMISIM#49]
Hi 
I attempted to check CAMISIM is working properly as per usage section guideline using the following command 

> python metagenomesimulation.py defaults/mini_config.ini

However, while at the "merging the bam files" steps it got aborted by giving the following error

> 2019-04-05 09:12:54 INFO: [Validator 17733368889] Creating pooled gold standard
> 2019-04-05 09:12:54 INFO: [Validator 17733368889] Merging bam files.
> 2019-04-05 09:14:18 ERROR: [MetagenomeSimulationPipeline] [Errno 12] Cannot allocate memory in line 111
> 2019-04-05 09:14:18 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
![Capture](https://user-images.githubusercontent.com/25049809/55598224-6b1c2780-579d-11e9-8f19-ac68ca742aec.PNG)

Can you please suggest what is going wrong with CAMISIM

Thanks in Advance

**Comment by AlphaSquad** [comment]
Hi,
please make sure that your machine has enough RAM and free space in either the directory where CAMISIM is stored and in the /tmp directory. You will need about 10 GB of free space and at least 4 GB RAM for the test run.
 If that does not help, could you run the command with the --debug flag set?
`python metagenomesimulation.py --debug defaults/mini_config.ini`
Then we can see where exactly stuff goes wrong.

**Comment by drashutosh** [comment]
Thanks @AlphaSquad 
I could manage it working by increasing the RAM of the virtual machine, However, I am getting issues when I am trying to import the reads.fq into qiime2 for downstream analysis, could you give me some suggestions?

**Comment by AlphaSquad** [comment]
Could you give more details on how these issues look like? Mind that CAMISIM produces the reads in a single interleaved fastq file while some tools might expect them to be in two files, I don't know whether that is the case for qiime2.

**Comment by drashutosh** [comment]
Yes, qiime2 expect them in two files, for example, Sample_1_R1.fastq.gz and Sample_1_R2.fastq.gz

**Comment by drashutosh** [comment]
Hi @Adrian 
I am trying 

> >> python metagenome_from_profile.py -p defaults/mini.biom -o out_profile --debug

I getting the following error messages

> 2019-04-11 12:26:06 INFO: [FastaAnonymizer] Interweave shuffle and anonymize
> 2019-04-11 12:26:06 DEBUG: [FastaAnonymizer] get_seeded_random() { seed="$1"; openssl enc -aes-256-ctr -pass pass:"$seed" -nosalt < /dev/zero 2>/dev/null; }; python '/home/ashutosh/Downloads/CAMISIM/fastastreamer.py' -input '/tmp/tmpt9lRxf/2019.04.11_10.24.00_sample_0/reads' -format 'fastq' -ext 'fq' | shuf -z --random-source=<(get_seeded_random 882634272391362167) | tr -d '\000' | python '/home/ashutosh/Downloads/CAMISIM/anonymizer.py' -prefix 'S0R' -format 'fastq' -map '/tmp/tmpt9lRxf/tmpzwIJBz' -out '/tmp/tmpt9lRxf/tmp3Uc541'
> shuf: read error: Cannot allocate memory
> Traceback (most recent call last):
>   File "/home/ashutosh/Downloads/CAMISIM/fastastreamer.py", line 280, in <module>
>     paired=not options.s
>   File "/home/ashutosh/Downloads/CAMISIM/fastastreamer.py", line 76, in stream_directory
>     self.interweave_stream(list_of_file, out_stream=out_stream, file_format=file_format, extension=extension)
>   File "/home/ashutosh/Downloads/CAMISIM/fastastreamer.py", line 213, in interweave_stream
>     out_stream.write(seq_record_f.format(file_format))
> IOError: [Errno 32] Broken pipe
> 2019-04-11 12:48:31 INFO: [MetadataReader 13724025753] Reading file: '/home/ashutosh/Downloads/CAMISIM/out_profile/internal/genome_locations.tsv'
> 2019-04-11 12:48:31 INFO: [MetadataReader 59399198286] Reading file: '/home/ashutosh/Downloads/CAMISIM/out_profile/internal/meta_data.tsv'
> 2019-04-11 12:48:31 INFO: [MetadataReader 66198569253] Reading file: '/tmp/tmpt9lRxf/tmpzwIJBz'
> 2019-04-11 12:48:31 DEBUG: [MetagenomeSimulationPipeline] 
> Traceback (most recent call last):
>   File "./metagenomesimulation.py", line 117, in run_pipeline
>     self._anonymize_data(list_of_output_gsa, file_path_output_gsa_pooled)
>   File "./metagenomesimulation.py", line 635, in _anonymize_data
>     file_path_genome_locations, file_path_metadata, file_path_anonymous_mapping_tmp, stream_output
>   File "/home/ashutosh/Downloads/CAMISIM/scripts/GoldStandardFileFormat/goldstandardfileformat.py", line 368, in gs_read_mapping
>     dict_anonymous_to_read_id = self.get_dict_anonymous_to_original_id(file_path_id_map)
>   File "/home/ashutosh/Downloads/CAMISIM/scripts/GoldStandardFileFormat/goldstandardfileformat.py", line 142, in get_dict_anonymous_to_original_id
>     dict_mapping = table.get_map(1, 0)
>   File "/home/ashutosh/Downloads/CAMISIM/scripts/MetaDataTable/metadatatable.py", line 613, in get_map
>     assert self.has_column(key_column_name), "Column '{}' not found!".format(key_column_name)
> AssertionError: Column '1' not found!
> 2019-04-11 12:48:31 ERROR: [MetagenomeSimulationPipeline] Column '1' not found! in line 117
> 2019-04-11 12:48:31 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
> 2019-04-11 12:48:31 INFO: [MetagenomeSimulationPipeline] Temporary data stored at:
> /tmp/tmpt9lRxf
> 

Does it a memory problem? I am running it on a virtual machine with 8GB RAM and 200 GB disk space on my machine
Can suggest what is going on

Thanks in advance

Ashutosh

**Comment by AlphaSquad** [comment]
In general, 8 GB RAM should suffice, but it sure looks like a memory problem:
> shuf: read error: Cannot allocate memory
Since that step failes, later on some expected values are missing, which causes the assertion error. Could you try it with 16 GB? I definitively was able to run that test on a 16 GB machine

**Comment by drashutosh** [comment]
Thanks  Adrian @AlphaSquad

**Comment by aspitaleri** [comment]
Hi,
I getting the same error. Below the last lines from 
python metagenomesimulation.py --debug defaults/mini_config.ini
2019-08-07 11:22:17 INFO: [FastaAnonymizer] Interweave shuffle and anonymize
2019-08-07 11:22:17 DEBUG: [FastaAnonymizer] get_seeded_random() { seed="$1"; openssl enc -aes-256-ctr -pass pass:"$seed" -nosalt < /dev/zero 2>/dev/null; }; python '/lustre2/scratch/Cirillo/SOFT
W/CAMISIM/fastastreamer.py' -input '/tmp/tmpPCfwc7/2019.08.07_11.12.55_sample_0/reads' -format 'fastq' -ext 'fq' | shuf -z --random-source=<(get_seeded_random 3808562586786140696) | tr -d '\000' 
| python '/lustre2/scratch/Cirillo/SOFTW/CAMISIM/anonymizer.py' -prefix 'S0R' -format 'fastq' -map '/tmp/tmpPCfwc7/tmpmd3a2M' -out '/tmp/tmpPCfwc7/tmpt6VS_Z'
shuf: '/dev/fd/63': end of file
2019-08-07 11:23:21 INFO: [MetadataReader 28632919956] Reading file: '/lustre2/scratch/Cirillo/SOFTW/CAMISIM/out/internal/genome_locations.tsv'
2019-08-07 11:23:23 INFO: [MetadataReader 44068977927] Reading file: '/lustre2/scratch/Cirillo/SOFTW/CAMISIM/out/internal/meta_data.tsv'
2019-08-07 11:23:23 INFO: [MetadataReader 76495163535] Reading file: '/tmp/tmpPCfwc7/tmpmd3a2M'
2019-08-07 11:23:23 DEBUG: [MetagenomeSimulationPipeline] 
Traceback (most recent call last):
  File "metagenomesimulation.py", line 117, in run_pipeline
    self._anonymize_data(list_of_output_gsa, file_path_output_gsa_pooled)
  File "metagenomesimulation.py", line 635, in _anonymize_data
    file_path_genome_locations, file_path_metadata, file_path_anonymous_mapping_tmp, stream_output
  File "/lustre2/scratch/Cirillo/SOFTW/CAMISIM/scripts/GoldStandardFileFormat/goldstandardfileformat.py", line 368, in gs_read_mapping
    dict_anonymous_to_read_id = self.get_dict_anonymous_to_original_id(file_path_id_map)
  File "/lustre2/scratch/Cirillo/SOFTW/CAMISIM/scripts/GoldStandardFileFormat/goldstandardfileformat.py", line 142, in get_dict_anonymous_to_original_id
    dict_mapping = table.get_map(1, 0)
  File "/lustre2/scratch/Cirillo/SOFTW/CAMISIM/scripts/MetaDataTable/metadatatable.py", line 613, in get_map
    assert self.has_column(key_column_name), "Column '{}' not found!".format(key_column_name)
AssertionError: Column '1' not found!
2019-08-07 11:23:23 ERROR: [MetagenomeSimulationPipeline] Column '1' not found! in line 117
2019-08-07 11:23:23 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
2019-08-07 11:23:23 INFO: [MetagenomeSimulationPipeline] Temporary data stored at:
/tmp/tmpPCfwc7
(base) [login1]

running on a cluster with:
#PBS -l nodes=1:ppn=1
#PBS -l mem=70GB
any help?
