### ISSUE TITLE
Can I use CAMISIM to simulate OTUs?

### ISSUE THREAD

**Issue by drashutosh** [CAMI-challenge/CAMISIM#51]
Hi 
I am just curious, If the input is a taxonomic profile in BIOM format, the OTUs appearing in it
Can I use CAMISIM to simulate OTUs?

Thanks in advance 
Ashutosh

**Comment by AlphaSquad** [comment]
I fear that I am not sure what exactly you want to achieve, how exactly do you want to "simulate" OTUs?

**Comment by drashutosh** [comment]
Actually, I want to simulate 16S rRNA (de novo) data set for differential abundance analysis, I have used 
`python metagenomesimulation.py defaults/mini_config.ini`
The output seems like genomic data, not 16s data, How to do it for 16S rRNA data?

**Comment by AlphaSquad** [comment]
I am afraid that CAMISIM will not be able to produce 16S rRNA. The procedures for amplicon sequencing and whole genome shotgun differ so much from one another that it would be hard to do with the current setup of CAMISIM.
