### ISSUE TITLE
No module named StringIO on standard command line

### ISSUE THREAD

**Issue by yoann-dufresne** [CAMI-challenge/CAMISIM#52]
Hi,

I'm trying to generate de novo metagenome samples using the default command line :
python metagenomesimulation.py defaults/mini_config.ini

At the very end of the simulation I have a python error that abort the whole process :

2019-04-24 16:24:11 INFO: [FastaAnonymizer] Interweave shuffle and anonymize
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/yoann/Softwares/CAMISIM/fastastreamer.py", line 9, in <module>
  File "/home/yoann/Softwares/CAMISIM/anonymizer.py", line 7, in <module>
    import StringIO
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
ModuleNotFoundError: No module named 'StringIO'
2019-04-24 16:24:11 ERROR: [FastaAnonymizer] Error occurred anonymizing '/tmp/tmpC8uquE/2019.04.24_16.19.24_sample_0/reads'
2019-04-24 16:24:11 ERROR: [MetagenomeSimulationPipeline] Error occurred anonymizing '/tmp/tmpC8uquE/2019.04.24_16.19.24_sample_0/reads' in line 117
2019-04-24 16:24:11 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted

The module StringIO is not found. This is very curious because if I understand well, this module is a part of the standard library.
This bug is reproducible under multiple linux computers.
Do you have any idea of what caused this issue ?

**Comment by AlphaSquad** [comment]
Could you find out which python version you are using (`which python`)?
I just read that in python3, there is no StringIO module anymore, so if you are not using python 2.7.* that would explain this error.
If this is not the case, could you send me your OS specs so I can set up a virtual machine for reproducing this bug?

**Comment by yoann-dufresne** [comment]
I was explicitly using python2.7.
I'm using ubuntu 18.04.

Thanks

**Comment by AlphaSquad** [comment]
Curious, I cannot see how this could happen with python2.7
Could you try using the provided docker container? 
`docker build -t camisim .`
`docker run camisim metagenomesimulation.py defaults/mini_config.ini`
I tried this - replacing the 16.04 in the Dockerfile with 18.04 - and it ran fine on my end.
Could you run this explicit command (if the problem persists):
`python2 metagenomesimulation.py --debug defaults/mini_config.ini` and post the log?
Thank you!

**Comment by yoann-dufresne** [comment]
It works fine with the docker.
So I can use it.

But here is the log file (stdin and stderr mixed) with a crash on my ubuntu 18.04
[exec.log](https://github.com/CAMI-challenge/CAMISIM/files/3117756/exec.log)

you're welcome :)

**Comment by yoann-dufresne** [comment]
Just to say that the problem is not still solved.
I am using a singularity container to have the same behaviour than the original python script.

I can reproduce the bug on two independent computers, so, I suspect a library version problem.

**Comment by AlphaSquad** [comment]
Right, re-opening this then. Could you post the exact versions of the required software tools (found in the [requirements.txt](https://github.com/CAMI-challenge/CAMISIM/blob/master/requirements.txt)) on your computers? Additionally, the log you sent is truncated as far as I can see, could you add a complete one (piping stderr and stdout?)
I don't have a computer with Ubuntu 18.04 at my disposal, so I can only test the docker with Ubuntu 18.04 and that was working fine.
