### ISSUE TITLE
Error on using wgsim with no errors

### ISSUE THREAD

**Issue by yoann-dufresne** [CAMI-challenge/CAMISIM#54]
I'm trying to run CASIM using wgsim with the noerror flag but the pipeline crashed.

Here is the command line that I used
python2.7 metagenomesimulation.py --debug defaults/mini_config_wgsim.ini
With the config file :
[mini_config_wgsim.txt](https://github.com/CAMI-challenge/CAMISIM/files/3122146/mini_config_wgsim.txt)

But the pipeline crashed on a python KeyError.
I think that is caused by a precedent warning/error raised :
2019-04-26 14:50:45 INFO: [GenomePreparation 75339803532] Simulating reads finished
[W::sam_read1] parse error at line 81
[main_samview] truncated file.
[W::sam_read1] parse error at line 3863
[main_samview] truncated file.
[W::sam_read1] parse error at line 9821
[main_samview] truncated file.
[W::sam_read1] parse error at line 38837
[main_samview] truncated file.
[W::sam_read1] parse error at line 71881
[main_samview] truncated file.
[W::sam_read1] parse error at line 216393
[main_samview] truncated file.

Here are the complete logs :
[exec_wgsim_stderr.txt](https://github.com/CAMI-challenge/CAMISIM/files/3122150/exec_wgsim_stderr.txt)

Do you have any idea on how to fix it ?

**Comment by AlphaSquad** [comment]
Is it possible that you still had some remains of the previous CAMISIM run present in that folder?
It looks like CAMISIM skipped over some parts of the pipeline because it noticed that files would be overwritten/are already present; but since the previous runs crashed (?), the files were not complete.

**Comment by yoann-dufresne** [comment]
It works fine with a cleaning before the execution.
The process ends correctly.

But I still have some warnings during the execution :
[wgsim_core] calculating the total length of the reference sequence...
[wgsim_core] 2 sequences, total length: 4773537
2019-04-29 13:23:10 INFO: [GenomePreparation 75339803532] Simulating reads finished
[W::sam_read1] parse error at line 81
[main_samview] truncated file.
[W::sam_read1] parse error at line 3863
[main_samview] truncated file.
[W::sam_read1] parse error at line 9821
[main_samview] truncated file.
[W::sam_read1] parse error at line 38837
[main_samview] truncated file.
[W::sam_read1] parse error at line 71881
[main_samview] truncated file.
[W::sam_read1] parse error at line 216393
[main_samview] truncated file.

**Comment by AlphaSquad** [comment]
I can reproduce the warnings, but for me it looks like the output is fine. 
I will investigate was causes these

**Comment by AlphaSquad** [comment]
After carefully checking the output and code it indeed was a bug in the creation of the samfile within wgsim if multiple sequences are present in the reference genome. Thanks for pointing this out! 944a232 should fix it, could you please confirm?
Thank you very much!

**Comment by yoann-dufresne** [comment]
I confirm.
Bug fixed
