### ISSUE TITLE
Simulation using a set of fasta files

### ISSUE THREAD

**Issue by yoann-dufresne** [CAMI-challenge/CAMISIM#55]
Hi,

I'm sorry but I don't understand if it's possible or not, to create metagenomic samples from my own fasta/fastq (for example, private genomes not yet published).

So, I would like to provide a bunch of fasta to camisim and then, let the software create the abundances, cut the reads and anonymise everything in a fq file.
Is it possible ? If yes, how can I do that ?

**Comment by AlphaSquad** [comment]
Actually this is one of the main use cases of CAMISIM! You will just need to create the [genome_to_id and metadata files](https://github.com/CAMI-challenge/CAMISIM/wiki/File-Formats) linking to your genomes, adapt the config files to your needs - add the previously created files, choose number of samples, size per sample, sequencing technology - and then you are good to go and can run metagenomesimulation.py your_config.ini
Please ask away if a specific problem arises

**Comment by AlphaSquad** [comment]
Did you manage to simulate a data set as you would expect or is there still some question open regarding this?
