### ISSUE TITLE
sequencing depth

### ISSUE THREAD

**Issue by plesan** [CAMI-challenge/CAMISIM#57]
Hi,

I am using camisim and I wonder if I can change the sequencing depth.
I do not see any parameters about this except the sample size parameter. Could you please help?

Best

**Comment by AlphaSquad** [comment]
Hi,
there is indeed no direct way to set sequencing depth as parameter. With a little manual effort you can use the "distribution_file_paths" option in which you can set the relative abundance of every genome you want to use. Multiplying the genome size with the desired coverage should give you an estimate of the sequencing depth, setting this as relative abundance and the sum of all the relative abundances as sample size should (roughly) give you the desired depth.

**Comment by AlphaSquad** [comment]
Did that help you, can I close this issue?

**Comment by plesan** [comment]
Hi,

Thanks a lot. Yes, I managed to do that. You can close this issue.

Best wishes
