### ISSUE TITLE
Can I simulate shotgun metagenome with my own genomes using CAMISIM? 

### ISSUE THREAD

**Issue by biofuture** [CAMI-challenge/CAMISIM#58]
Hi,

I have 25 bacterial genomes sequences that not listed in the NCBI genome database. Can I simulate a microbial community with the 25 genomes with CAMI?

I also want to adjust the abundance profile of the different genomes at different simulation.

Thank you very much.

**Comment by AlphaSquad** [comment]
Hi,
thanks for your interest in CAMISIM.
Actually, using your own genomes is one of the main ideas of CAMISIM. If you want to adjust the abundance profiles of your genomes manually anyway (using the abundance files/distribution_file_paths option), then the only thing you need to do is set your own genomes' names and metadata in the [genome_to id and metadata](https://github.com/CAMI-challenge/CAMISIM/wiki/File-Formats) files and you are good to go.

**Comment by biofuture** [comment]
Thanks for the tips. 

I have successfully run the mini_config.ini simulation.   I have some genomes that are not in the NCBI database, so there is no NCBI taxid.   How can I  make the metadata.tsv file in this scenario?   Do I  must have the metadata.tsv file to do the simulation?  I tried to replace the taxid otuid into the meaninless number, the simulation stop with "Metagenome simulation aborted" NCBItaxonomy  invalid taxid  8. 

I would like to generate simulated shotgun metagenomes with totally my genomes without taxid.  

Thank you very much.

**Comment by biofuture** [comment]
my metadata.tsv, so the OTU and NCBI_ID are just  added as increasing number

genome_ID       OTU     NCBI_ID novelty_category
Genome1 1       1       new_species
Genome2 2       2       new_species
Genome3 3       3       new_species
Genome4 4       4       new_species
Genome5 5       5       new_species
Genome6 6       6       new_species
Genome7 7       7       new_species
Genome8 8       8       new_species
Genome9 9       9       new_species
Genome10        10      10      new_species
Genome11        11      11      new_species
Genome12        12      12      new_species
Genome13        13      13      new_species
Genome14        14      14      new_species
Genome15        15      15      new_species
Genome16        16      16      new_species
Genome17        17      17      new_species
Genome18        18      18      new_species
Genome19        19      19      new_species
Genome20        20      20      new_species
Genome21        21      21      new_species
Genome22        22      22      new_species
Genome23        23      23      new_species
Genome24        24      24      new_species

**Comment by AlphaSquad** [comment]
For creating the taxonomic binning and profiling gold standards, CAMISIM requires a taxon ID. If you are not interested in these gold standards, you unfortunately still have to provide a valid taxonomic ID. I would recommend just using the tax ID '2' for all genomes then (for bacteria).
Please let me know if this solution works for you

**Comment by AlphaSquad** [comment]
Did that work for you? If yes, could you please close this issue?

**Comment by biofuture** [comment]
Thanks, it works.  I would like to know after I assigned the taxon 2 to these genomes. There are gold standard contigs.  Can they be used as the gold standard for the bins?

**Comment by AlphaSquad** [comment]
The binning gold standard will map back to the genomes they originated from, so it should be usable, yes. Taxonomic binning and the profiling gold standards will not make too much sense though.
