### ISSUE TITLE
ART error profile 'hi'

### ISSUE THREAD

**Issue by AlphaSquad** [CAMI-challenge/CAMISIM#6]
The Pipeline "recommends" ART 2.3.6, but actually breaks for ART 2.3.7, because the profile 'hi' (namely the files EmpHiSeq2kR1.txt and EmpHiSeq2kR2.txt) are missing in the folder vor ART 2.3.7
See also suggestion in #5 (using files directly instead of folder)

**Comment by abremges** [comment]
@AlphaSquad Please comment on this. From my understanding, we use the MBARC-26 profile by default now and this is resolved? If so, close this issue.

**Comment by AlphaSquad** [comment]
MBARC-26 profile is used as standard error profile and the ART version is shipped within CAMISIM
