### ISSUE TITLE
genome_ID and NCBI_ID

### ISSUE THREAD

**Issue by aspitaleri** [CAMI-challenge/CAMISIM#68]
Dear all,
the genome_ID number in 
https://github.com/CAMI-challenge/CAMISIM/blob/master/documentation/CAMI2015_metadata_final.tsv
where is from?
I need to generate a set of sample with fixed taxonomy so I will use distributions_file_path in the config file. For that I need to know the genome_ID which as far as I understood is an internal number different to NCBI_ID.
Thanks!

**Comment by AlphaSquad** [comment]
The genome_ID is just some number/identifier, it does not hold any specific information. It is just used for mapping the metadata to the abundances and the genome files. Note that this metadata file was used for the CAMI1 challenge in 2015 - so it is quite old and is likely not compatible with the current version of CAMISIM in case you wanted to use that specific file.

**Comment by aspitaleri** [comment]
Thanks @AlphaSquad . Okay so it is just an internal index in the metadata file. Just to be sure that I am doing right. the option distributions_file_path in the config file defines the relative abundance of the bacteria present in the final fastq file. The file should be like:
1<tab>45
2<tab>25
3<tab>30

where 1,2,3 refers to 3 different genome_ID bacteria defined in the config file in
metadata=
id_to_genome_file=
id_to_gff_file=

thanks!

**Comment by AlphaSquad** [comment]
The abundance files are just simple tab separated file with genome_ID \t relative abundance, so in your case genomes 1, 2, 3:
<pre>1    45
2    25
3    30</pre>
would have the relative abundances of 45, 25, 30.
The genome IDs 1, 2, 3 need to be identical to the genome ID in the metadata and genome\_to_id files, correct. The id\_to\_gff\_file is only required if you intend to use simulated strains

**Comment by aspitaleri** [comment]
ok perfetc! actually my example was with tab ....
Thanks!
