### ISSUE TITLE
Line 80 KeyError with default sequences

### ISSUE THREAD

**Issue by longg2** [CAMI-challenge/CAMISIM#74]
Hi there,

I'm trying to run a simulation using specific abundances, however, I'm running into a key error that I haven't been able to figure out.  The default sequences are being used.

Distribution File:
> Genome16.0 \t 0.9
> Genome19.0 \t 0.02
> Genome15.0 \t 0.02
> Genome9.0 \t 0.02
> Genome14.0 \t 0.02
> Genome8.0 \t 0.02

Output using `./metagenomesimulation.py -debug defaults/default_config.ini` :
> 2020-01-27 16:12:46 INFO: [MetagenomeSimulationPipeline] Metagenome simulation starting
> 2020-01-27 16:12:46 INFO: [MetagenomeSimulationPipeline] Validating Genomes
> 2020-01-27 16:12:46 INFO: [MetadataReader] Reading file: '/home/sam/CAMISIM/defaults/genome_to_id.tsv'
> 2020-01-27 16:13:15 INFO: [MetadataReader 62530393383] Reading file: '/home/sam/CAMISIM/defaults/metadata.tsv'
> 2020-01-27 16:13:15 INFO: [MetadataReader 62915486388] Reading file: '/home/sam/PropTesting/internal/genome_locations.tsv'
> 2020-01-27 16:13:16 INFO: [NcbiTaxonomy] Building taxonomy tree...
> 2020-01-27 16:13:16 INFO: [NcbiTaxonomy] Reading 'nodes' file:  '/tmp/tmpVZYtwa/NCBI/nodes.dmp' 
> 2020-01-27 16:13:29 INFO: [NcbiTaxonomy] Reading 'names' file:  '/tmp/tmpVZYtwa/NCBI/names.dmp' 
> 2020-01-27 16:13:31 INFO: [NcbiTaxonomy] Reading 'merged' file: '/tmp/tmpVZYtwa/NCBI/merged.dmp'
> 2020-01-27 16:13:31 INFO: [NcbiTaxonomy] Done (15.0s)
> 2020-01-27 16:13:31 DEBUG: [MetagenomeSimulationPipeline]  
> Traceback (most recent call last):
>   File "./metagenomesimulation.py", line 80, in run_pipeline
>     self.write_profile_gold_standard(meta_data_table, list_of_file_paths_distributions)
>   File "./metagenomesimulation.py", line 203, in write_profile_gold_standard
>     sample_id=""         
>   File "/home/sam/CAMISIM/scripts/ComunityDesign/taxonomicprofile.py", line 58, in write_taxonomic_profile_from_abundance_files
>     sample_id)
>   File "/home/sam/CAMISIM/scripts/ComunityDesign/taxonomicprofile.py", line 89, in write_taxonomic_profile
>     self._stream_taxonomic_profile(stream_output, genome_abundance, metadata_table, sample_id)
>   File "/home/sam/CAMISIM/scripts/ComunityDesign/taxonomicprofile.py", line 124, in _stream_taxonomic_profile
>     column_strain_id[row_index] = genome_id_to_strain_id[genome_id]
> KeyError: 'Genome11.0'   
> 
> 
> 2020-01-27 16:13:31 ERROR: [MetagenomeSimulationPipeline] 'Genome11.0' in line 80
> 2020-01-27 16:13:31 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
> 2020-01-27 16:13:31 INFO: [MetagenomeSimulationPipeline] Temporary data stored at:
> /tmp/tmpehgUg2                                                                      

I've also attached a config file should it be needed.
[ProportionTesting.txt](https://github.com/CAMI-challenge/CAMISIM/files/4119431/ProportionTesting.txt)

Cheers

**Comment by AlphaSquad** [comment]
Hi,
thank you for using CAMISIM. Is the distribution file you attached complete?
From the config file I see that you are using the default metadata/genome_to_id files which contain 25 genomes. Out of these, 6 will get chosen with your config file. Unfortunately, CAMISIM is not "smart" enough to choose the 6 genomes you specified in your distributions file.
There are two alternatives which will hopefully achieve what you want to do:
1. Editing the metadata/genome_to_id files such that they only contain the 6 genomes you specify in the distribution file or
2. Adding the remaining 19 genomes with a relative abundance of 0.0 (and changing the config file to 25 genomes being simulated)
In both cases you should end up with only sequences for the 6 genomes with the desired relative abundances.

I hope this helps and please ask away if something is unclear
Best,
Adrian

**Comment by longg2** [comment]
Hi Adrian,

This was exactly what I needed.

Thanks!
