### ISSUE TITLE
Could you give me a simplify example on how you calculate the values of recall and precison?

### ISSUE THREAD

**Issue by tenlives** [CAMI-challenge/CAMISIM#78]
Hello,
I want know to  the unit of the recall and precision , is the unit an experiment ? or a bin of assembly experiment result ?  Thank you

**Comment by AlphaSquad** [comment]
Hi,
unfortunately I am not sure whether I can follow you. In what context are you talking about recall and precision? How does CAMISIM come into play?

**Comment by tenlives** [comment]
> Hi,
> unfortunately I am not sure whether I can follow you. In what context are you talking about recall and precision? How does CAMISIM come into play?
