### ISSUE TITLE
May I use CAMISIM to produce many samples with different genomes subset in a given genome set?

### ISSUE THREAD

**Issue by tenlives** [CAMI-challenge/CAMISIM#79]
hi,
  I want to downsample a given genome set to produce  many simulated illumina reads samples with  different genomes . Can I do it use CAMISIM ?  Thank you !

**Comment by AlphaSquad** [comment]
Hi,
yes that should be possible, you would need to do the downsampling beforehand by yourself though. If you want to use a different set of genomes every sample that would be a little harder, and probably more handywork - but should still be possible. If that's what you are interested in, feel free to ask again, I will try to work something out then.

**Comment by tenlives** [comment]
> Hi,
> yes that should be possible, you would need to do the downsampling beforehand by yourself though. If you want to use a different set of genomes every sample that would be a little harder, and probably more handywork - but should still be possible. If that's what you are interested in, feel free to ask again, I will try to work something out then.

Thank you for replying,  I can do the downsampling before use CAMISIM.  May I  set different seed values in mini_config.ini  to get different samples  to run  CAMISIM for many times  ?  Thank you very much.

**Comment by AlphaSquad** [comment]
Sure, that's exactly what this parameter is for!

**Comment by tenlives** [comment]
Thank you for replying. I want to ask you anther question about the option "anonymous" in mini_config.ini, for every read  in the situation of  "True" and "False" options , they  have the same genome name if I set the same seed value?

**Comment by AlphaSquad** [comment]
Yes, that should be the case
