### ISSUE TITLE
NCBI taxdump file

### ISSUE THREAD

**Issue by ShaopengLiu1** [CAMI-challenge/CAMISIM#81]
Hello,

This is Shaopeng, thanks for developing CAMISIM, it's awesome!

I want to confirm some information of ncbi_taxdump file used in metagenomesimulation.py.
Is the provided taxdump file a wrapper of the ncbi taxonomy files (which can be downloaded from: https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/)?

In the "tools" folder, there are 2 versions of the taxdump file: "2017" and "2018". When I tried a newer version downloaded directly from the NCBI FTP database and then I got the following message:
```
2020-07-05 22:38:07 INFO: [CommunityDesign] Validating raw sequence files!
2020-07-05 22:38:58 ERROR: [NcbiTaxonomy] Directory does not exist: '/tmp/tmp54dBf9/gencode.dmp'
2020-07-05 22:38:58 ERROR: [MetagenomeSimulationPipeline]  in line 83
2020-07-05 22:38:58 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
```

My cmd is exactly same with the tutorial, but only change the corresponding files in "mini_config.ini"

So I untar the original file you provided and found that the only difference is that there is one folder "NCBI" containing every file, so I rearranged the downloaded file and it seems that CAMISIM can run with it. Is this the correct way to use different taxdump file?

Thank you!

**Comment by AlphaSquad** [comment]
Hello Shaopeng,
thank you very much for your kind words and your interest in CAMISIM. What you described is indeed the correct way to use another NCBI taxdump and it is great that you made it work. 
This problem already came up earlier and I think it would be preferable if a new taxdump would work out of the box without having to add the `NCBI` parent directory, I will see what I can do.

**Comment by ShaopengLiu1** [comment]
Thank you!
