### ISSUE TITLE
Error running with metagenome_from_profile.py

### ISSUE THREAD

**Issue by zhengzhengzhj** [CAMI-challenge/CAMISIM#84]
Hi all, 
I just installed CAMISIM yesterday, and I am new in running  CAMISIM. 
When I try to run created data from a profile file with the command "python metagenome_from_profile.py -p defaults/mini.biom  -tmp /tmp", I get the error message. Here is the screenshot. 

![image](https://user-images.githubusercontent.com/18700180/92042574-1a1cb400-ed40-11ea-8f8b-c4da2a399444.png)

Could anyone who can help me figure out his problem?

**Comment by AlphaSquad** [comment]
Hi, is this the very first run of CAMISIM you tried? This error sometimes occurs if the directory CAMISIM tries to write to contains remainders of previous CAMISIM runs. This might either be the directory specified in the config file (if you did not change the config file this will be ./out) or in the /tmp directory.

**Comment by zhengzhengzhj** [comment]
> Hi, is this the very first run of CAMISIM you tried? This error sometimes occurs if the directory CAMISIM tries to write to contains remainders of previous CAMISIM runs. This might either be the directory specified in the config file (if you did not change the config file this will be ./out) or in the /tmp directory.
