### ISSUE TITLE
Custom Taxonomy

### ISSUE THREAD

**Issue by punnettsun** [CAMI-challenge/CAMISIM#90]
Hello,

If we have our own taxonomy files similar to nodes.dmp, names.dmp, etc. like in the NCBI taxonomy, can we generate our own datasets based on our own custom IDs and taxonomic information? Or is CAMISIM specifically only able to use the NCBI taxonomy?

Thank you.

**Comment by AlphaSquad** [comment]
If this taxonomy follows NCBIs naming convention, then it should possible to use your own dump. I haven't tried that yet though, so you might run into unforeseeable troubles. If you do, please feel free to open another issue.
In any case this will not be compatible with creating a metagenome from a BIOM profile though.

**Comment by punnettsun** [comment]
The taxonomy is based closer to GTBD. I think this might not work then.

Thank you for your help.
