### ISSUE TITLE
Using Scaffolds and Configs in Simulated Reads

### ISSUE THREAD

**Issue by Tj-Idowu** [CAMI-challenge/CAMISIM#91]
I'm trying to simulate a real-life environmental sample and have done taxonomic assignment on a metagenomic sample. A lot of my results came back as microbes that have not had their whole genome sequenced yet but have scaffolds or configs available as reference. My question is should I use these scaffolds and configs when simulating my metagenome or should I leave them out and only use organisms with whole genomes?

**Comment by AlphaSquad** [comment]
Hi,
that is a good question, but the answer depends on what you want to achieve with the simulated metagenome. If you want a complex set and as many genomes present from your original sample as possible then you can use the scaffolds and contigs. If you a re looking to reconstruct complete genomes or want to use long reads it probably makes more sense to limit yourself to the complete genomes.
In our experiments we usually include complete genomes and scaffolds, but remove genomes/scaffolds with too many and too short contigs, e.g. all fasta files with more than 100 contigs and/or contigs with less then 5kb. This provides a tradeoff between accurately reflecting the original sample and still being able to recover longer genome sequences later on.
