### ISSUE TITLE
custom abundance profile doesn't reflect abundance in output

### ISSUE THREAD

**Issue by NienkeMekkes** [CAMI-challenge/CAMISIM#92]
Dear author,

I am simulating a sample using metagenomesimulation.py, a de novo community, and a custom abundance profile.
Everything works, I only noticed that my output abundance does not reflect my input abundance.

Example of how my input abundance.tsv looks like:
Genome1	0.06
Genome2	0.06
Genome3	0.06

In the output file reads_mappings, when I count all reads belonging to Genome1, divide them by two (forward/reverse) and take that number as a percentage of total reads, I get 18% in stead of 6%. The output of Kraken2 on this simulated metagenome also gives 18% for Genome1. Is this normal behavior, or is it expected that the final abundance is very different from the input abundance? If so, why is that?

Kind regards

my config.ini:
[Main]
seed=632741178
phase=0
max_processors=8
dataset_id=zymotest
output_directory=simulations/sim_zymo_no_error/out
temp_directory=/tmp
gsa=False
pooled_gsa=False
anonymous=True
compress=1

[ReadSimulator]
readsim=CAMISIM/tools/wgsim/wgsim
error_profiles=.
samtools=CAMISIM/tools/samtools-1.3/samtools
profile=
size=1.0
type=wgsim
fragments_size_mean=270
fragment_size_standard_deviation=27

[CommunityDesign]
#distribution_file_paths='out/abundance0.tsv', 'out/abundance1.tsv', 'out/abundance2.tsv', 'out/abundance3.tsv', 'out/abundance4.tsv', 'out/abundance5.tsv', 'out/abundance6.tsv', 'out/abundance7.tsv', 'out/abundance8.tsv', 'out/abundance9.tsv'
ncbi_taxdump=simulations/sim_zymo_no_error/taxonomy/NCBI/
strain_simulation_template=CAMISIM/scripts/StrainSimulationWrapper/sgEvolver/simulation_dir
number_of_samples=1
distribution_file_paths=simulations/sim_zymo_no_error/abundance.tsv

[community0]
metadata=simulations/sim_zymo_no_error/metadata.tsv
id_to_genome_file=simulations/sim_zymo_no_error/genome_to_id.tsv
id_to_gff_file=
genomes_total=21
genomes_real=21
max_strains_per_otu=5
ratio=1
mode=differential
log_mu=1
log_sigma=2
gauss_mu=1
gauss_sigma=1
view=True

**Comment by AlphaSquad** [comment]
Hi,

thank you for using CAMISIM! There seems to be a common misunderstanding - which our documentation is to blame for - that the values in the abundance.tsv files are _absolute_ abundance values. Instead these are _relative_ values. If your abundances sum up to 1, these abundance values should coincide though. 
Additionally, different genome sizes might cause unexpected results depending on the definition of "abundance": Given Genome1 with length x and Genome2 with length 2*x and both with an abundance of 0.5 in the abundance.tsv file, the resulting dataset will comprise of 66.6% reads belonging to Genome2 and 33.3% of reads belonging to Genome1, such that every base of Genome1 and Genome2 is covered roughly the same amount of times. If you created 50% of reads for Genome1 and 50% of reads for Genome2 then Genome2 will be covered half as much as Genome1. 
If your genomes all have similar sizes this should not be that much of a difference. If they do have vastly different sizes and you want the abundance to reflect the amount of reads and not the genome coverage you would need to multiply the abundance values with a scaling factor (_c_/genome_size with some positive constant _c_)

Using the config file you show might be problematic in another way though: The option for using custom abundance files (_distribution\_file\_paths_) seems to be commented out, so CAMISIM will use the differential mode for creating abundances (specified under _mode_ in the _community0_ section). Can you retry your run, removing the leading '#' in front of the _distribution\_file\_paths_ option and I think you will need to remove the apostrophe (') around the paths of your abundance files.
I am sorry for your confusion and I will try to improve the documentation of that option.

**Comment by NienkeMekkes** [comment]
Hello,

Thanks for the clear explanation and the example. I've recalculated my abundance values, and now there is a near perfect match between my input abundance and the abundance profiles generated by bracken. 

Many thanks!
