### ISSUE TITLE
python 2.6.10 is so old

### ISSUE THREAD

**Issue by xuechunxu** [CAMI-challenge/CAMISIM#93]
Does the python 3.6 or newer version can work? Several dependencies are not support python 2.6.10 you used.

**Comment by AlphaSquad** [comment]
Overhauling CAMISIM such that it works with recent python versions (i.e. python3) certainly is something we would like to do but do not have the manpower to do so currently.

**Comment by AlphaSquad** [comment]
There is a [python3](https://github.com/CAMI-challenge/CAMISIM/tree/python3) branch available now which you could test. It passed my tests and it would be appreciated if you could also have a look.

**Comment by AlphaSquad** [comment]
`python3` has been merged into `master`
