### ISSUE TITLE
Error in from_profile test

### ISSUE THREAD

**Issue by elder099** [CAMI-challenge/CAMISIM#98]
I seem to be getting a package version error when running:
python metagenome_from_profile.py -p defaults/mini.biom

Here are the relevant packages/python I have in my conda environment:
biom-format               2.1.7                    py27_0    bioconda
biopython                 1.74             py27h7b6447c_0  
numpy                     1.16.6           py27hbc911f0_0  
numpy-base                1.16.6           py27hde5b4d6_0  
python                    2.7.10                        2 
scipy                     1.2.1            py27h7c811a0_0  

Here's the ERROR I'm getting:

Traceback (most recent call last):
  File "metagenome_from_profile.py", line 11, in <module>
    import scripts.get_genomes as GG
  File "/tempalloc/noyes042/elder099/CAMISIM/CAMISIM/scripts/get_genomes.py", line 5, in <module>
    import biom
  File "/home/noyes046/elder099/lib/biom_format-2.1.8.dev0-py3.7-linux-x86_64.egg/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/home/noyes046/elder099/lib/biom_format-2.1.8.dev0-py3.7-linux-x86_64.egg/biom/table.py", line 177, in <module>
    import scipy.stats
  File "/home/noyes046/elder099/lib/scipy-1.5.3-py3.7-linux-x86_64.egg/scipy/__init__.py", line 77, in <module>
    _fun = _deprecated(_msg.format(_key))(_fun)
  File "/home/noyes046/elder099/lib/scipy-1.5.3-py3.7-linux-x86_64.egg/scipy/_lib/deprecation.py", line 16, in wrap
    @functools.wraps(fun)
  File "/tempalloc/noyes042/elder099/CAMISIM/CAMIpy/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'

From what I understand, it's a problem with scipy and numpy versions in python 2.7.
Any suggestions?

**Comment by AlphaSquad** [comment]
Could you try the python3 branch and see if the problem persists. It is likely that this version will get ported to the master branch, because there will probably only be more problems with python2.7 as time goes on

**Comment by Apurbz** [comment]
I have the same problem when running:
python metagenome_from_profile.py -p defaults/mini.biom

I am using python 3. 

Is this problem solved?
Any suggestions?

**Comment by AlphaSquad** [comment]
Could you try the `python3` _branch_ of CAMISIM (the main branch of CAMISIM is written in python2.7) and see if this solves the problem?

**Comment by Apurbz** [comment]
Thanks a lot for your reply.
And it works now but has some problems like after test run, in Github, it
was written that in the output there will be a new folder which will be
approximately 2.4GB but in my case, I have only 190 MB and I noticed that
Some files are empty for example Bam files.
Is it because of large files are deleted, like samtools?

Thanks again and eagerly waiting for your reply.

BR
Apurbha Saha.

**Comment by AlphaSquad** [comment]
As long as CAMISIM terminated without errors (i.e. the last output is "Metagenome simulation finished") then I would assume that everything is in order. You could check in your `defaults/default_config.ini` to what the `size` parameter is set. If it is still set to 5 (GB) then something is definitely missing, but I would need to see CAMISIMs log to be able to do debugging

**Comment by Apurbhasaha** [comment]
Thanks again for your feedback. 
But i found an error at last. and the output was following ......... (As i mention before is it for Samtools )?
Please give me a feedback .
Best Regards.

Here is the last outputs: 

/home/saha/new/CAMISIM-python3/tools/samtools-1.3/samtools: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory
/home/saha/new/CAMISIM-python3/tools/samtools-1.3/samtools: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory

2021-02-09 01:17:02 INFO: [MetagenomeSimulationPipeline] Generate gold standard assembly
2021-02-09 01:17:02 INFO: [MetadataReader 16932406861] Reading file: '/home/saha/new/CAMISIM-python3/out/internal/genome_locations.tsv'
2021-02-09 01:17:02 ERROR: [MetagenomeSimulationPipeline] Empty bam file list in line 106
2021-02-09 01:17:02 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted

**Comment by AlphaSquad** [comment]
Hm, that looks like you haven't installed the libncursesw library. Could you try (re-)installing it? Which operating system are you using?

**Comment by Apurbz** [comment]
Thanks for your reply.
 i am using linex operating system Ubuntu 20.04.

**Comment by AlphaSquad** [comment]
Could you try this: https://askubuntu.com/questions/1252062/how-to-install-libncurses-so-5-in-ubuntu-20-04

**Comment by Apurbhasaha** [comment]
Thanks for reply .
Unfortunately ,its not solved . I got the same last output result as before. i attach 2 screenshot here . Now , what should i do?
Best Regards.

> 
![Screenshot from 2021-02-09 10-29-12](https://user-images.githubusercontent.com/74571252/107343857-14cb4e80-6ac2-11eb-943e-c40eeedd8288.png)
![Screenshot from 2021-02-09 10-31-24](https://user-images.githubusercontent.com/74571252/107343860-1563e500-6ac2-11eb-8715-17f91e3ad976.png)

output as before.

**Comment by AlphaSquad** [comment]
Sorry that I haven't reacted for so long, this is very hard to debug. Could you try manually installing samtools-1.3 and link to your own executable in the `config.ini` file?
